/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.MedicalDoctorRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import ui.LoginScreen;

/**
 *
 * @author bbpri
 */
public class MedicalDoctorWorkAreaJPanel extends javax.swing.JPanel {
    
    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;


    /**
     * Creates new form MedicalDoctorWorkAreaJPanel
     */
    public MedicalDoctorWorkAreaJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        this.account=account;
        this.organization=organization;
        this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoctorEnterprise = new javax.swing.JLabel();
        btnReview = new javax.swing.JButton();
        btnPrescribeTreatment = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblDoctorEnterprise.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblDoctorEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoctorEnterprise.setText("Doctor Enterprise");

        btnReview.setBackground(new java.awt.Color(153, 153, 255));
        btnReview.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReview.setForeground(new java.awt.Color(255, 255, 255));
        btnReview.setText("Review Health Data");
        btnReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewActionPerformed(evt);
            }
        });

        btnPrescribeTreatment.setBackground(new java.awt.Color(153, 153, 255));
        btnPrescribeTreatment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrescribeTreatment.setForeground(new java.awt.Color(255, 255, 255));
        btnPrescribeTreatment.setText("Prescribe Treatment");
        btnPrescribeTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescribeTreatmentActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 153, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnReview)
                    .addComponent(btnPrescribeTreatment)
                    .addComponent(lblDoctorEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblDoctorEnterprise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnReview, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnPrescribeTreatment)
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewActionPerformed
        // TODO add your handling code here:                                          
    // Navigate to ReviewHealthDataJPanel
        ReviewHealthDataJPanel rjp = new ReviewHealthDataJPanel(splitPane, account, organization, system);
        splitPane.setRightComponent(rjp);

    }//GEN-LAST:event_btnReviewActionPerformed

    private void btnPrescribeTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescribeTreatmentActionPerformed
        // TODO add your handling code here:    
        // Navigate to PrescribeTreatmentJPanel
        PrescribeTreatmentJPanel rjp = new PrescribeTreatmentJPanel(splitPane, account, system, system);
        splitPane.setRightComponent(rjp);
    }//GEN-LAST:event_btnPrescribeTreatmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginScreen login=new LoginScreen(splitPane, system);
        splitPane.setRightComponent(login);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrescribeTreatment;
    private javax.swing.JButton btnReview;
    private javax.swing.JLabel lblDoctorEnterprise;
    // End of variables declaration//GEN-END:variables
}
