/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.MedicalDoctorRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanaabena
 */
public class PrescribeTreatmentJPanel extends javax.swing.JPanel {

     private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;
    private Student student;
    
    /**
     * Creates new form PrescribeTreatmentJPanel
     */
    public PrescribeTreatmentJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
       initComponents();
        this.splitPane=splitPane;
        this.account=account;
        this.organization=organization;
        this.system=system;
        
        populateStudentComboBox();
    }
    
    /**
     * Populate the student's details into the form fields.
     */
    private void populateStudentComboBox() {
        cmbStudents.removeAllItems();
        Organization org = system.getOrganizationDirectory().findOrganization(Organization.Type.Student);
        org.getStudentDirectory().getStudentList();
        System.out.println("Student List is as follows ");
        for(Student s:org.getStudentDirectory().getStudentList()){
            System.out.println(s);
            cmbStudents.addItem(s);
        }
        
        populatePrescribeTable((Student) cmbStudents.getSelectedItem());
    }
    
    private void populatePrescribeTable(Student selectedstudent) {
        
           // Fetch the table model
    DefaultTableModel model = (DefaultTableModel) tblPrescribe.getModel();
    model.setRowCount(0); // Clear existing rows
    // Get the selected student's name from the combo box
    String selectedStudentName = cmbStudents.getSelectedItem().toString();
    if (selectedStudentName == null || selectedStudentName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a student.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Find the selected student from the organization
    Organization org = system.getOrganizationDirectory().findOrganization(Organization.Type.Student);
    if (org == null) {
        JOptionPane.showMessageDialog(this, "Student organization not found!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Fetch the student list and find the matching student
    ArrayList<Student> studentList = org.getStudentDirectory().getStudentList();
    Student selectedStudent = null;
    for (Student student : studentList) {
        if (student.getName().equals(selectedStudentName)) {
            selectedStudent = student;
            break;
        }
    }


    // Validate that the selected student exists
    if (selectedStudent == null) {
        JOptionPane.showMessageDialog(this, "Selected student not found!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Populate the table with the selected student's prescription data
    String date = txtDate.getText().trim();               // Date entered
    String diagnosis = txtStudentDiagnosis.getText().trim(); // Diagnosis entered
    String prescription = txtPrescription.getText().trim(); // Prescription entered

    // Add the data to the table
    Object[] row = new Object[]{
        selectedStudent.getName(), // Student Name
        date,                     // Date
        diagnosis,                // Diagnosis
        prescription              // Prescription
    };
    model.addRow(row);

    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblDoctorsPrescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrescription = new javax.swing.JTextArea();
        lblStudentDiagnosis = new javax.swing.JLabel();
        txtStudentDiagnosis = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        cmbStudents = new javax.swing.JComboBox();
        lblStudentName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPrescribe = new javax.swing.JTable();
        txtDate = new javax.swing.JTextField();
        lblDoctorsFeedback = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFeedback = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 255));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prescribe Treatment");

        lblDoctorsPrescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDoctorsPrescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorsPrescription.setText("Doctor's Presciption:");

        txtPrescription.setColumns(20);
        txtPrescription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPrescription.setRows(5);
        jScrollPane1.setViewportView(txtPrescription);

        lblStudentDiagnosis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentDiagnosis.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentDiagnosis.setText("Student's Diagnosis:");

        txtStudentDiagnosis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtStudentDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentDiagnosisActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmbStudents.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbStudents.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStudentsActionPerformed(evt);
            }
        });

        lblStudentName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentName.setText("Student's Name:");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Date:");

        tblPrescribe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblPrescribe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Date", "Student Diagnosis", "Doctors Prescription", "Doctor's Feedback"
            }
        ));
        jScrollPane2.setViewportView(tblPrescribe);

        txtDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblDoctorsFeedback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDoctorsFeedback.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorsFeedback.setText("Doctor's Feedback:");

        txtFeedback.setColumns(20);
        txtFeedback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFeedback.setRows(5);
        jScrollPane3.setViewportView(txtFeedback);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblStudentDiagnosis)
                                            .addComponent(txtStudentDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblDoctorsPrescription)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDoctorsFeedback)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(368, 368, 368))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStudentName)
                                    .addComponent(cmbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(171, 171, 171)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDate)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)))
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStudentName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStudentDiagnosis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudentDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDoctorsPrescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDoctorsFeedback, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:                                                                               
    try {
        // Retrieve selected student from the combo box
        Student selectedStudent = (Student) cmbStudents.getSelectedItem();

        // Validate that a student is selected
        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(this, "Please select a student.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Retrieve input values from the fields
        String date = txtDate.getText().trim();
        String diagnosis = txtStudentDiagnosis.getText().trim();
        String prescription = txtPrescription.getText().trim();

        // Validate that all fields are filled
        if (date.isEmpty() || diagnosis.isEmpty() || prescription.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled out before saving.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

//        // Add the data to the selected student's treatment history 
//        selectedStudent.setDiagnosis(diagnosis);
//        selectedStudent.setTreatmentPrescription(prescription);

        // Update the table with the entered data
        DefaultTableModel model = (DefaultTableModel) tblPrescribe.getModel();
        model.addRow(new Object[]{
            selectedStudent.getName(), // Student Name
            date,                      // Date
            diagnosis,                 // Diagnosis
            prescription               // Prescription
        });

        // Clear input fields for new data entry
        txtDate.setText("");
        txtStudentDiagnosis.setText("");
        txtPrescription.setText("");

        // Confirmation message
        JOptionPane.showMessageDialog(this, "Treatment prescribed and saved successfully!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An error occurred while saving: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnSaveActionPerformed

    
    
    /**
     * Navigate back to the Medical Doctor Work Area Panel.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MedicalDoctorWorkAreaJPanel pwajp = new MedicalDoctorWorkAreaJPanel(splitPane,account,system ,system);
        splitPane.setRightComponent(pwajp);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStudentsActionPerformed
        // TODO add your handling code here:
        Student selectedStudent = (Student) cmbStudents.getSelectedItem();

        if (selectedStudent != null){
            populatePrescribeTable(selectedStudent);
        }
    }//GEN-LAST:event_cmbStudentsActionPerformed

    private void txtStudentDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentDiagnosisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoctorsFeedback;
    private javax.swing.JLabel lblDoctorsPrescription;
    private javax.swing.JLabel lblStudentDiagnosis;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JTable tblPrescribe;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtFeedback;
    private javax.swing.JTextArea txtPrescription;
    private javax.swing.JTextField txtStudentDiagnosis;
    // End of variables declaration//GEN-END:variables
}
