/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.MedicalDoctorRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyWorkRequest;
import Business.WorkQueue.TeacherChatWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import ui.Organization.TeacherRole.TeacherWorkAreaJPanel;

/**
 *
 * @author nanaabena
 */
public class ReviewHealthDataJPanel extends javax.swing.JPanel {
    
    private JSplitPane splitPane;
    private UserAccount sender;
    private Organization organization;
    private EcoSystem system;
    EmergencyWorkRequest emergencyWorkRequest;
    
    /**
     * Creates new form ReviewHealthDataJPanel
     */
    public ReviewHealthDataJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        this.sender=account;
        this.organization=organization;
        this.system=system;
        populateTable();

//        populateStudentDetails();
//        populateParentTeacherComments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtStudentName = new javax.swing.JTextField();
        lblStudentName = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblReview = new javax.swing.JLabel();
        lblDoctorsComments = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDoctorsComments = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblWorkRequest = new javax.swing.JTable();
        btnAssignSelf = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(204, 204, 255));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtStudentName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        lblStudentName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentName.setText("Student's Name:");

        btnSave.setBackground(new java.awt.Color(153, 153, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Send");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblReview.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblReview.setForeground(new java.awt.Color(255, 255, 255));
        lblReview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReview.setText("Review Health Data");

        lblDoctorsComments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDoctorsComments.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorsComments.setText("Doctor's Comments:");

        txtDoctorsComments.setColumns(20);
        txtDoctorsComments.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDoctorsComments.setRows(5);
        jScrollPane2.setViewportView(txtDoctorsComments);

        tblWorkRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Reciver", "Status"
            }
        ));
        jScrollPane3.setViewportView(tblWorkRequest);

        btnAssignSelf.setBackground(new java.awt.Color(153, 153, 255));
        btnAssignSelf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAssignSelf.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignSelf.setText("Assign to me");
        btnAssignSelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignSelfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(125, 125, 125)
                        .addComponent(lblReview))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAssignSelf)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblDoctorsComments)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStudentName)
                                .addGap(37, 37, 37)
                                .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblReview))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAssignSelf)
                        .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblDoctorsComments))
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:  
         System.out.println("Inside acknowledge");
        int selectedRow = tblWorkRequest.getSelectedRow();
        if (selectedRow >= 0) {
            emergencyWorkRequest = (EmergencyWorkRequest) tblWorkRequest.getValueAt(selectedRow, 0);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a request message to process.");
            return;
        }
        
        if (txtDoctorsComments.getText().equals("") || txtDoctorsComments.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a resolution to send.");
            return;
        }
        
        
        emergencyWorkRequest.setResultMessage(txtDoctorsComments.getText());
        emergencyWorkRequest.setStatus("Resolved");
        populateTable();
        JOptionPane.showMessageDialog(null, "Message processed");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
                                       
        MedicalDoctorWorkAreaJPanel pwajp = new MedicalDoctorWorkAreaJPanel(splitPane,sender,system ,system);
        splitPane.setRightComponent(pwajp);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignSelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignSelfActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWorkRequest.getSelectedRow();

        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) tblWorkRequest.getValueAt(selectedRow, 0);
            if (request.getMessage().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already acknowledged and completed.");
                return;
            } else {
                request.setReceiver(sender);
                request.setStatus("Assigned");

                populateTable();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Choose a reuest to acknowledge.");
            return;
        }
    }//GEN-LAST:event_btnAssignSelfActionPerformed

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblWorkRequest.getModel();

        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getEmergencyWorkRequest()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee() == null ? null : request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();

            model.addRow(row);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignSelf;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDoctorsComments;
    private javax.swing.JLabel lblReview;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JTable tblWorkRequest;
    private javax.swing.JTextArea txtDoctorsComments;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
