/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.ParentRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Parent.Parent;
import Business.Roles.ParentRole;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Image;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.util.Map;

import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author bbpri
 */
public class StudentsAcademicProgress extends javax.swing.JPanel {

    public EcoSystem system;
    private JSplitPane splitPane;
    private UserAccount sender;
    Parent parent;
    private Image originalImage1;
    double totalMarks;
    String grade;
    double cgpa;

    /**
     * Creates new form StudentsAcademicProgress
     */
    public StudentsAcademicProgress(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane = splitPane;
        this.system = system;
        this.sender = account;
        this.parent = account.getParent();
        try {
            URL imageURL1 = getClass().getResource("/images/academic2.jpg");
            if (imageURL1 != null) {
                originalImage1 = ImageIO.read(imageURL1);
                System.out.println("Image 1 found");
            } else {
                System.err.println("Image1 not found");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        populateParentMarksTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMarks = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblGrade = new javax.swing.JLabel();
        txtgpa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();
        lblGrade1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnOverall = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        tblMarks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblMarks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Test Name", " English", "Maths", "French", "Social", "Science", "Feedback"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMarks);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblGrade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGrade.setForeground(new java.awt.Color(255, 255, 255));
        lblGrade.setText("Grade");

        txtgpa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Students Academic Progress");

        btnback.setBackground(new java.awt.Color(153, 153, 255));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/academic2.jpg"))); // NOI18N

        txtGrade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblGrade1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGrade1.setForeground(new java.awt.Color(255, 255, 255));
        lblGrade1.setText("CGPA");

        btnView.setBackground(new java.awt.Color(153, 153, 255));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnOverall.setBackground(new java.awt.Color(153, 153, 255));
        btnOverall.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOverall.setForeground(new java.awt.Color(255, 255, 255));
        btnOverall.setText("Overall Performance");
        btnOverall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverallActionPerformed(evt);
            }
        });

        btnDownload.setBackground(new java.awt.Color(153, 153, 255));
        btnDownload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDownload.setForeground(new java.awt.Color(255, 255, 255));
        btnDownload.setText("Download Pdf");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(lblGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOverall)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnView)
                                .addGap(139, 139, 139)
                                .addComponent(btnDownload)))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnback)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblGrade)
                                .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnOverall))
                            .addComponent(lblGrade1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnView)
                            .addComponent(btnDownload))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        ParentsWorkAreaJPanel pwajp = new ParentsWorkAreaJPanel(splitPane, sender, system, system);
        splitPane.setRightComponent(pwajp);

    }//GEN-LAST:event_btnbackActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMarks.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to view details!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblMarks.getModel();
        String testName = (String) model.getValueAt(selectedRow, 0);
        int englishMarks = (int) model.getValueAt(selectedRow, 1);
        int mathsMarks = (int) model.getValueAt(selectedRow, 2);
        int frenchMarks = (int) model.getValueAt(selectedRow, 3);
        int socialMarks = (int) model.getValueAt(selectedRow, 4);
        int scienceMarks = (int) model.getValueAt(selectedRow, 5);
        String feedback = (String) model.getValueAt(selectedRow, 6);

        ViewStudentAcademicProgressJPanel viewPanel = new ViewStudentAcademicProgressJPanel(splitPane, sender, system, testName, englishMarks, mathsMarks, frenchMarks, socialMarks, scienceMarks, feedback);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnOverallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverallActionPerformed
        // TODO add your handling code here:
        

        Parent parent = sender.getParent();
        if (parent == null) {
            JOptionPane.showMessageDialog(null, "Parent details not found for the logged-in user!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        for (Student student : parent.getStudent()) {
            for (String testName : student.getTestMarks().keySet()) {
                Map<String, Integer> marks = student.getMarksForTest(testName);
                dataset.addValue(marks.getOrDefault("English", 0), "English", testName);
                dataset.addValue(marks.getOrDefault("Maths", 0), "Maths", testName);
                dataset.addValue(marks.getOrDefault("French", 0), "French", testName);
                dataset.addValue(marks.getOrDefault("Social", 0), "Social", testName);
                dataset.addValue(marks.getOrDefault("Science", 0), "Science", testName);
            }
        }
    
        showBarChart(dataset);


    }//GEN-LAST:event_btnOverallActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblMarks.getModel();

        String path = "";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int selection = fileChooser.showSaveDialog(this);

        if (selection == JFileChooser.APPROVE_OPTION) {
            path = fileChooser.getSelectedFile().getPath();
        } else {
            JOptionPane.showMessageDialog(this, "Export canceled.");
            return;
        }

        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(path + "/StudentMarksReport.pdf"));
            document.open();

            PdfPTable pdfTable = new PdfPTable(model.getColumnCount());

            for (int col = 0; col < model.getColumnCount(); col++) {
                pdfTable.addCell(model.getColumnName(col));
            }

            for (int row = 0; row < model.getRowCount(); row++) {
                for (int col = 0; col < model.getColumnCount(); col++) {
                    Object cellValue = model.getValueAt(row, col);
                    pdfTable.addCell(cellValue != null ? cellValue.toString() : "");
                }
            }

            document.add(pdfTable);

            JOptionPane.showMessageDialog(this, "PDF downloaded successfully at " + path);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error generating PDF: " + e.getMessage());
        } finally {
            document.close();
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void populateParentMarksTable() {
        DefaultTableModel model = (DefaultTableModel) tblMarks.getModel();
        model.setRowCount(0);

        //To check if the logged in user is parent
        if (!(sender.getRole() instanceof ParentRole)) {
            JOptionPane.showMessageDialog(null, "Logged-in user is not assigned the ParentRole!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Parent parent = sender.getParent();
        if (parent == null) {
            JOptionPane.showMessageDialog(null, "Parent details not found for the logged-in user!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (Student student : parent.getStudent()) {
            for (String testName : student.getTestMarks().keySet()) {
                Map<String, Integer> marks = student.getMarksForTest(testName);
                int englishMarks = marks.getOrDefault("English", 0);
                int mathsMarks = marks.getOrDefault("Maths", 0);
                int frenchMarks = marks.getOrDefault("French", 0);
                int socialMarks = marks.getOrDefault("Social", 0);
                int scienceMarks = marks.getOrDefault("Science", 0);
                String feedback = student.getFeedbackTest(testName);

                Object[] row = new Object[]{
                    testName,
                    englishMarks,
                    mathsMarks,
                    frenchMarks,
                    socialMarks,
                    scienceMarks,
                    feedback
                };
                model.addRow(row);
            }
            // Get total marks
            totalMarks = student.getTotalMarks();
            txtTotal.setText(String.valueOf(totalMarks));
            System.out.println("Total Marks: " + totalMarks);

            // Get grade
            grade = student.getGrade_Score();
            System.out.println("Grade: " + grade);
            txtGrade.setText(grade);

            // Get CGPA
            cgpa = student.getCGPA();
            System.out.println("CGPA: " + cgpa);
            txtgpa.setText(String.valueOf(cgpa));
        }
    }

private void showBarChart(DefaultCategoryDataset dataset) {
    // Create the bar chart
    JFreeChart chart = ChartFactory.createBarChart(
        "Subject-Wise Test Performance", // Chart title
        "Tests",                         // X-axis Label
        "Marks",                         // Y-axis Label
        dataset,                         // Dataset
        PlotOrientation.VERTICAL,        // Orientation
        true,                            // Include legend
        true,                            // Tooltips
        false                            // URLs
    );

    // Create a panel to display the chart
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(800, 600));

    // Display the chart in a new JFrame
    JFrame chartFrame = new JFrame("Subject-Wise Performance Chart");
    chartFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    chartFrame.getContentPane().add(chartPanel);
    chartFrame.pack();
    chartFrame.setVisible(true);
}

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnOverall;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblGrade1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblMarks;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtgpa;
    // End of variables declaration//GEN-END:variables
}
