/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.ParentRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Parent.Parent;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author bbpri
 */
public class ViewHealthReportJPanel extends javax.swing.JPanel {

    public EcoSystem system;
    private JSplitPane splitPane;
    private UserAccount sender;
    Parent parent;

    /**
     * Creates new form ViewHealthReportJPanel
     */
    public ViewHealthReportJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane = splitPane;
        this.system = system;
        this.sender = account;
        this.parent = account.getParent();
        for (Student student : parent.getStudent()) {
            lblheight.setText(String.valueOf(student.getHeight()));
            lblweight.setText(String.valueOf(student.getWeight()));
            lblage.setText(String.valueOf(student.getAge()));
            lblgender.setText(student.getGender());
            lblbmi.setText(student.getBmiCategory());
            try {
                // Check if the student's meal plan is empty or null
                if (student.getMealPlan() == null || student.getMealPlan().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No Suggestion from the nutritionist yet", "Info", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                // Set the meal plan in the text area
                txtmeal.setText(student.getMealPlan());
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Error: Student information is missing or incomplete.", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
                 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail6 = new javax.swing.JLabel();
        lblEmail5 = new javax.swing.JLabel();
        lblweight = new javax.swing.JLabel();
        lblheight = new javax.swing.JLabel();
        lblEmail2 = new javax.swing.JLabel();
        lblbmi = new javax.swing.JLabel();
        lblEmail3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmeal = new javax.swing.JTextArea();
        lblage = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnback1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblEmail6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail6.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail6.setText("Gender");

        lblEmail5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail5.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail5.setText("Age");

        lblweight.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblweight.setForeground(new java.awt.Color(255, 255, 255));
        lblweight.setText("<Weight>");

        lblheight.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblheight.setForeground(new java.awt.Color(255, 255, 255));
        lblheight.setText("<Height>");

        lblEmail2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail2.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail2.setText("Height");

        lblbmi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblbmi.setForeground(new java.awt.Color(255, 255, 255));
        lblbmi.setText("<BMI>");

        lblEmail3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail3.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail3.setText("Weight");

        txtmeal.setEditable(false);
        txtmeal.setColumns(20);
        txtmeal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtmeal.setRows(5);
        jScrollPane2.setViewportView(txtmeal);

        lblage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblage.setForeground(new java.awt.Color(255, 255, 255));
        lblage.setText("<Age>");

        lblgender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblgender.setForeground(new java.awt.Color(255, 255, 255));
        lblgender.setText("<Gender>");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Meal plan Suggestion from Nutritionist");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Health Report");

        btnback1.setBackground(new java.awt.Color(153, 153, 255));
        btnback1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnback1)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblbmi, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblweight, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblheight, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnback1))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail2)
                            .addComponent(lblheight))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail3)
                            .addComponent(lblweight)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail5)
                            .addComponent(lblage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail6)
                            .addComponent(lblgender))))
                .addGap(27, 27, 27)
                .addComponent(lblbmi)
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        ParentsWorkAreaJPanel pwajp = new ParentsWorkAreaJPanel(splitPane, sender, system, system);
        splitPane.setRightComponent(pwajp);
    }//GEN-LAST:event_btnback1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEmail3;
    private javax.swing.JLabel lblEmail5;
    private javax.swing.JLabel lblEmail6;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblbmi;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lblweight;
    private javax.swing.JTextArea txtmeal;
    // End of variables declaration//GEN-END:variables
}
