/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.SportsEventManagerRole;

import Business.Business.EcoSystem;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

import Business.Events.Event;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import com.github.lgooddatepicker.components.DateTimePicker;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JSplitPane;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanaabena
 */
public class OrganizeEventsJPanel extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;

    /**
     * Creates new form OrganizeEventsJPanel
     */
    public OrganizeEventsJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane = splitPane;
        this.account = account;
        this.organization = organization;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrganizeEvents = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtEventName = new javax.swing.JTextField();
        lblEventName = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        txtAudience = new javax.swing.JTextField();
        lblAudience = new javax.swing.JLabel();
        lblVenue = new javax.swing.JLabel();
        txtVenue = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEvents = new javax.swing.JTable();
        dateTimePicker = new com.github.lgooddatepicker.components.DateTimePicker();

        setBackground(new java.awt.Color(204, 204, 255));

        lblOrganizeEvents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrganizeEvents.setText("Organize Events");
        lblOrganizeEvents.setBackground(new java.awt.Color(255, 255, 255));
        lblOrganizeEvents.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblOrganizeEvents.setForeground(new java.awt.Color(255, 255, 255));

        btnBack.setText("<< Back");
        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setBackground(new java.awt.Color(153, 153, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtEventName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEventNameActionPerformed(evt);
            }
        });

        lblEventName.setText("Event's Name:");
        lblEventName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEventName.setForeground(new java.awt.Color(255, 255, 255));

        lblDateTime.setText("Date & Time:");
        lblDateTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDateTime.setForeground(new java.awt.Color(255, 255, 255));

        txtAudience.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAudience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAudienceActionPerformed(evt);
            }
        });

        lblAudience.setText("Audience:");
        lblAudience.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAudience.setForeground(new java.awt.Color(255, 255, 255));

        lblVenue.setText("Venue:");
        lblVenue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVenue.setForeground(new java.awt.Color(255, 255, 255));

        txtVenue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVenueActionPerformed(evt);
            }
        });

        tblEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event Name", "Date&Time", "Venue", "Audience"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEvents.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(tblEvents);

        dateTimePicker.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrganizeEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEventName)
                            .addComponent(lblDateTime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAudience, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVenue, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAudience, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(198, 251, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganizeEvents)
                    .addComponent(btnBack))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateTime)
                    .addComponent(dateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVenue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAudience, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAudience))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAudience, txtEventName});

    }// </editor-fold>//GEN-END:initComponents

    private void txtEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventNameActionPerformed

    private void txtAudienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAudienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAudienceActionPerformed

    private void txtVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVenueActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:                                      
        try {
            // Retrieve input values
            String eventName = txtEventName.getText().trim();
            LocalDateTime selectedDateTime = dateTimePicker.getDateTimeStrict();

            if (selectedDateTime != null) {
                JOptionPane.showMessageDialog(this, "Selected Date and Time: " + selectedDateTime);
                // TODO: Add logic to save or process the selected date and time
            } else {
                JOptionPane.showMessageDialog(this, "Please select a valid date and time.", "Error", JOptionPane.ERROR_MESSAGE);
            }
//            String dateTime = txtDateTime.getText().trim();
            String dateTime = String.valueOf(selectedDateTime);
            String venue = txtVenue.getText().trim();
            String audience = txtAudience.getText().trim();

            // Validate inputs
            if (eventName.isEmpty() || dateTime.isEmpty() || venue.isEmpty() || audience.isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields must be filled out before saving.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Create a new Event object
            Event event = new Event(eventName, dateTime, venue, audience);

            // Save the event to the system
            system.addEvent(event);
//        organization.getEventDirectory().addEvent(event);

            // Update the table
            DefaultTableModel model = (DefaultTableModel) tblEvents.getModel();
            model.setRowCount(0);
            model.addRow(new Object[]{eventName, dateTime, venue, audience});

            // Clear input fields
            txtEventName.setText("");
            dateTimePicker.clear();
            txtVenue.setText("");
            txtAudience.setText("");

            // Confirmation message
            JOptionPane.showMessageDialog(this, "Event saved and added to the table successfully!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred while saving the event: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here
        SportsEventManagerWorkAreaJPanel pwajp = new SportsEventManagerWorkAreaJPanel(splitPane, account, system, system);
        splitPane.setRightComponent(pwajp);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAudience;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblEventName;
    private javax.swing.JLabel lblOrganizeEvents;
    private javax.swing.JLabel lblVenue;
    private javax.swing.JTable tblEvents;
    private javax.swing.JTextField txtAudience;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
