/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.SportsEventManagerRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JSplitPane;
import ui.LoginScreen;

/**
 *
 * @author bbpri
 */
public class SportsEventManagerWorkAreaJPanel extends javax.swing.JPanel {
    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;

    /**
     * Creates new form SportsEventManagerWorkAreaJPanel
     */
    public SportsEventManagerWorkAreaJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        this.account=account;
        this.organization=organization;
        this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrganizeEvents = new javax.swing.JButton();
        lblSportsEventManagement = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        btnOrganizeEvents.setBackground(new java.awt.Color(153, 153, 255));
        btnOrganizeEvents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrganizeEvents.setForeground(new java.awt.Color(255, 255, 255));
        btnOrganizeEvents.setText("Organize Sports Event");
        btnOrganizeEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizeEventsActionPerformed(evt);
            }
        });

        lblSportsEventManagement.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblSportsEventManagement.setForeground(new java.awt.Color(255, 255, 255));
        lblSportsEventManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSportsEventManagement.setText("Sports Event Management");

        btnLogout.setBackground(new java.awt.Color(153, 153, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSportsEventManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrganizeEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSportsEventManagement)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(169, 169, 169)
                .addComponent(btnOrganizeEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrganizeEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizeEventsActionPerformed
        // TODO add your handling code here:                                        
   OrganizeEventsJPanel pwajp = new OrganizeEventsJPanel(splitPane,account,system ,system);
        splitPane.setRightComponent(pwajp);
    }//GEN-LAST:event_btnOrganizeEventsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginScreen login = new LoginScreen(splitPane, system);
        splitPane.setRightComponent(login);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrganizeEvents;
    private javax.swing.JLabel lblSportsEventManagement;
    // End of variables declaration//GEN-END:variables
}
