/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.ParentRole;

import Business.Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.EnterpriseNetwork;
import Business.Organization.NutritionistOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NutritionistChatWorkRequest;
import Business.WorkQueue.TeacherChatWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bbpri
 */
public class ChatWithNutritionist extends javax.swing.JPanel {
    private JSplitPane splitPane;
    private UserAccount sender;
    private Organization organization;
    private EcoSystem system;
    private Image originalImage1;
    private Image originalImage2;
    private Image originalImage3;

    /**
     * Creates new form ChatWithNutritionist
     */
    public ChatWithNutritionist(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        this.splitPane = splitPane;
        this.sender = account;
        this.organization = organization;
        this.system = system;
        try {
            URL imageURL1 = getClass().getResource("/images/nu2.jpg");
            URL imageURL2 = getClass().getResource("/images/man.png");
            URL imageURL3 = getClass().getResource("/images/Medical-Pharmacist-Female-Light-icon.png");
            if (imageURL1 != null) {
                originalImage1 = ImageIO.read(imageURL1);
                System.out.println("Image 1 found");
            } else {
                System.err.println("Image1 not found");
            }
            if (imageURL2 != null) {

                originalImage2 = ImageIO.read(imageURL2);
                System.out.println("Image 2 found");
            } else {
                System.err.println("Image2 not found");
            }
            if (imageURL3 != null) {
                originalImage3 = ImageIO.read(imageURL3);
                System.out.println("Image 3 found");
            } else {
                System.err.println("Image3 not found");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        initComponents();
        
        System.out.println("Hello from chatwithNutritionist constructor");
        populateRequestTable();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPMessage = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        lblparent1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResolution = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChatHistory = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        btnback1 = new javax.swing.JButton();
        txtNName = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chat With Nutritionist");

        txtPMessage.setColumns(20);
        txtPMessage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPMessage.setRows(5);
        jScrollPane1.setViewportView(txtPMessage);

        btnSend.setBackground(new java.awt.Color(153, 153, 255));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        lblparent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Medical-Pharmacist-Female-Light-icon.png"))); // NOI18N

        txtResolution.setColumns(20);
        txtResolution.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtResolution.setRows(5);
        jScrollPane2.setViewportView(txtResolution);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Chat History");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nutritionist Name: ");

        tblChatHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblChatHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Recipient", "Status", "Reply"
            }
        ));
        jScrollPane3.setViewportView(tblChatHistory);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nu2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        txtStatus.setBackground(new java.awt.Color(153, 153, 255));
        txtStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 255, 255));
        txtStatus.setText("Pending");

        btnback1.setBackground(new java.awt.Color(153, 153, 255));
        btnback1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        txtNName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnRefresh.setBackground(new java.awt.Color(153, 153, 255));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSend))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnback1)
                                    .addComponent(lblparent1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel1))))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnback1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSend)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblparent1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(btnRefresh)
                                .addGap(47, 47, 47)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
          String reqMessage = txtPMessage.getText();
        if (reqMessage.equals("") || reqMessage.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a message to send.");
            return;
        }

        NutritionistChatWorkRequest message = new NutritionistChatWorkRequest();
        message.setMessage(reqMessage);
        message.setSender(sender);
        message.setStatus("Sent");
//        message.setReceiver(cmbTeacher.getSelectedItem());
        txtStatus.setText("Sent");

        Organization orgn = null;
        for (EnterpriseNetwork network : system.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                //Step 3:check against each organization for each enterprise
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof NutritionistOrganization) {
                        orgn = organization;
                        break;
                    }
                }
            }
        }

        System.out.println("Whats the organization " + orgn);
        if (orgn != null) {
            orgn.getWorkQueue().getWorkRequestNutritionList().add(message);
            System.out.println("inside send button " + orgn.getWorkQueue().getWorkRequestNutritionList().get(0));
            sender.getWorkQueue().getWorkRequestNutritionList().add(message);
        }

        JOptionPane.showMessageDialog(null, "Request message sent", "Information", JOptionPane.INFORMATION_MESSAGE);
        //txtMessage.setText("");
//        txtCSRName.setText("Agent not assigned");
        populateRequestTable();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        ParentsWorkAreaJPanel pwajp = new ParentsWorkAreaJPanel(splitPane,sender,system ,system);
        splitPane.setRightComponent(pwajp);
    }//GEN-LAST:event_btnback1ActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:

        populateRequestTable();
        int size = sender.getWorkQueue().getWorkRequestNutritionList().size();
        WorkRequest result = sender.getWorkQueue().getWorkRequestNutritionList().get(size - 1);
        txtResolution.setText(((NutritionistChatWorkRequest) result).getResultMessage());
        if (((NutritionistChatWorkRequest) result).getReceiver() != null) {
            txtNName.setText(((NutritionistChatWorkRequest) result).getReceiver().getEmployee().getName());
        }
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnback1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblparent1;
    private javax.swing.JTable tblChatHistory;
    private javax.swing.JTextField txtNName;
    private javax.swing.JTextArea txtPMessage;
    private javax.swing.JTextArea txtResolution;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

 public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblChatHistory.getModel();
        System.out.println("Hello inside table" + sender.getWorkQueue().getWorkRequestNutritionList());
        model.setRowCount(0);
        for (WorkRequest request : sender.getWorkQueue().getWorkRequestNutritionList()) {
            System.out.println("Hello from table" + request.getMessage());
            Object[] row = new Object[4];
            row[0] = request.getMessage();
//          cmbTeacher.getSelectedItem();
//            row[1] = cmbTeacher.getSelectedItem();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            String result = ((NutritionistChatWorkRequest) request).getResultMessage();
            row[3] = result == null ? "Waiting" : result;

            model.addRow(row);
        }
    }
}
