/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.ParentRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Parent.Parent;
import Business.Roles.ParentRole;
import Business.Student.Student;
import Business.UserAccount.UserAccount;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import ui.LoginScreen;

/**
 *
 * @author bbpri
 */
public class ParentsWorkAreaJPanel extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;

    /**
     * Creates new form ParentsJPanel
     */
    public ParentsWorkAreaJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane = splitPane;
        this.account = account;
        this.organization = organization;
        this.system = system;
        System.out.println("Organization in parent work area" + organization);
        System.out.println("system in parent work area" + system);
        Parent currentParent = account.getParent();
        System.out.println("Name of child display "+currentParent);
        if (currentParent != null) {
            System.out.println("Parent Name: " + currentParent.getName());
            for (Student child : currentParent.getStudent()) {
                System.out.println("Child: " + child.getName());
                lblCName.setText(child.getName());
                lblImage.setIcon(child.getLogoImage());
            }
        } else {
            System.out.println("No parent linked to the account!");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTrackAcademic = new javax.swing.JButton();
        btnTeacherChat = new javax.swing.JButton();
        btnHealthReport = new javax.swing.JButton();
        btnNutriyonistChat = new javax.swing.JButton();
        btnSportsProgress = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblCName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        btnTrackAcademic.setBackground(new java.awt.Color(153, 153, 255));
        btnTrackAcademic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrackAcademic.setForeground(new java.awt.Color(255, 255, 255));
        btnTrackAcademic.setText("Track Students Academic progress");
        btnTrackAcademic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackAcademicActionPerformed(evt);
            }
        });

        btnTeacherChat.setBackground(new java.awt.Color(153, 153, 255));
        btnTeacherChat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTeacherChat.setForeground(new java.awt.Color(255, 255, 255));
        btnTeacherChat.setText("Chat with teacher");
        btnTeacherChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherChatActionPerformed(evt);
            }
        });

        btnHealthReport.setBackground(new java.awt.Color(153, 153, 255));
        btnHealthReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHealthReport.setForeground(new java.awt.Color(255, 255, 255));
        btnHealthReport.setText("View Health Report");
        btnHealthReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHealthReportActionPerformed(evt);
            }
        });

        btnNutriyonistChat.setBackground(new java.awt.Color(153, 153, 255));
        btnNutriyonistChat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNutriyonistChat.setForeground(new java.awt.Color(255, 255, 255));
        btnNutriyonistChat.setText("Chat with Nutritonist");
        btnNutriyonistChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNutriyonistChatActionPerformed(evt);
            }
        });

        btnSportsProgress.setBackground(new java.awt.Color(153, 153, 255));
        btnSportsProgress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSportsProgress.setForeground(new java.awt.Color(255, 255, 255));
        btnSportsProgress.setText("Track Sports Performance");
        btnSportsProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSportsProgressActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 153, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Child Name");

        lblCName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCName.setForeground(new java.awt.Color(255, 255, 255));
        lblCName.setText("<Child Name>");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Parents DashBoard");

        lblImage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblImage.setText("<No Image>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTeacherChat, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTrackAcademic)
                            .addComponent(btnNutriyonistChat, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHealthReport, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSportsProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 413, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(lblCName)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrackAcademic)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTeacherChat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnNutriyonistChat)
                .addGap(30, 30, 30)
                .addComponent(btnHealthReport)
                .addGap(28, 28, 28)
                .addComponent(btnSportsProgress)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeacherChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherChatActionPerformed
        // TODO add your handling code here:
        ChatWithTeacher cwt = new ChatWithTeacher(splitPane, account, organization, system);
        splitPane.setRightComponent(cwt);
    }//GEN-LAST:event_btnTeacherChatActionPerformed

    private void btnHealthReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHealthReportActionPerformed
        // TODO add your handling code here:
        ViewHealthReportJPanel cwt = new ViewHealthReportJPanel(splitPane, account, organization, system);
        splitPane.setRightComponent(cwt);
    }//GEN-LAST:event_btnHealthReportActionPerformed

    private void btnNutriyonistChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNutriyonistChatActionPerformed
        // TODO add your handling code here:
        ChatWithNutritionist cwt = new ChatWithNutritionist(splitPane, account, organization, system);
        splitPane.setRightComponent(cwt);
    }//GEN-LAST:event_btnNutriyonistChatActionPerformed

    private void btnSportsProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSportsProgressActionPerformed
        // TODO add your handling code here:
        TrackSportsPerformanceJPanel sap = new TrackSportsPerformanceJPanel(splitPane, account, organization, system);
        splitPane.setRightComponent(sap);
    }//GEN-LAST:event_btnSportsProgressActionPerformed

    private void btnTrackAcademicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackAcademicActionPerformed
        // TODO add your handling code here:
        System.out.println(account);
        StudentsAcademicProgress sap = new StudentsAcademicProgress(splitPane, account, organization, system);
        splitPane.setRightComponent(sap);
    }//GEN-LAST:event_btnTrackAcademicActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginScreen login = new LoginScreen(splitPane, system);
        splitPane.setRightComponent(login);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHealthReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNutriyonistChat;
    private javax.swing.JButton btnSportsProgress;
    private javax.swing.JButton btnTeacherChat;
    private javax.swing.JButton btnTrackAcademic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables
}
