/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.ParentRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Parent.Parent;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bbpri
 */
public class TrackSportsPerformanceJPanel extends javax.swing.JPanel {
    public EcoSystem system;
    private JSplitPane splitPane;
    private UserAccount sender;
    Parent parent;

    /**
     * Creates new form TrackSportsPerformanceJPanel
     */
    public TrackSportsPerformanceJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        this.splitPane = splitPane;
        this.system = system;
        this.sender=account;
        this.parent=account.getParent();
        initComponents();
        Student student = parent.getStudent().get(0);
        populatePerformanceTable(student);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPerformance = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        btnback.setBackground(new java.awt.Color(153, 153, 255));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Track Students Sports Performance");

        tblPerformance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblPerformance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Game Played", "Speed", "Endurance", "Strength", "Mental Focus", "Performance Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPerformance);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnback)
                    .addComponent(jLabel2))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        ParentsWorkAreaJPanel pwajp = new ParentsWorkAreaJPanel(splitPane,sender,system ,system);
        splitPane.setRightComponent(pwajp);
    }//GEN-LAST:event_btnbackActionPerformed

private void populatePerformanceTable(Student selectedStudent) {
        DefaultTableModel model = (DefaultTableModel) tblPerformance.getModel();
        model.setRowCount(0); // Clear existing rows

        Map<String, Map<String, String>> performances = selectedStudent.getGamePerformances();

        for (Map.Entry<String, Map<String, String>> gameEntry : performances.entrySet()) {
            String gameName = gameEntry.getKey();
            Map<String, String> performance = gameEntry.getValue();

            String performanceScore = performance.get("PerformanceScore");
            System.out.println("Performance score in pop table " + performanceScore);
            System.out.println("Retrieving performance for game " + gameName + ": " + performance);
            if (performanceScore == null || performanceScore.isEmpty()) {
                System.out.println("PerformanceScore is missing for game: " + gameName);
                performanceScore = "0"; // Assign a default value
            }

            // Retrieve performance attributes
            String speed = performance.getOrDefault("Speed", null);
            String strength = performance.getOrDefault("Strength", null);
            String endurance = performance.getOrDefault("Endurance", null);
            String mentalFocus = performance.getOrDefault("MentalFocus", null);

            // String performanceScore = performance.getOrDefault("PerformanceScore", performanceScore1);
            // Ensure performanceScore is parsable
            int parsedScore = 0;
            try {
                parsedScore = Integer.parseInt(performanceScore);
            } catch (NumberFormatException e) {
                System.out.println("Invalid PerformanceScore: " + performanceScore);
                JOptionPane.showMessageDialog(this, "Invalid performance score for game: " + gameName, "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Add a row to the table
            Object[] row = new Object[]{
                gameName, // Game Name
                speed, // Speed
                strength, // Strength
                endurance, // Endurance
                mentalFocus, // Mental Focus
                parsedScore,};
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPerformance;
    // End of variables declaration//GEN-END:variables
}
