/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.ParentRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Parent.Parent;
import Business.UserAccount.UserAccount;
import java.awt.Image;
import javax.swing.JSplitPane;

/**
 *
 * @author bbpri
 */
public class ViewStudentAcademicProgressJPanel extends javax.swing.JPanel {
    public EcoSystem system;
    private JSplitPane splitPane;
    private UserAccount sender;
    Parent parent;
    private Image originalImage1;
    double totalMarks;
    String grade;
    double cgpa;
    /**
     * Creates new form ViewStudentAcademicProgressJPanel
     */
    public ViewStudentAcademicProgressJPanel(JSplitPane splitPane, UserAccount account, EcoSystem system, String testName, int english, int maths, int french, int social, int science, String feedback) {
        initComponents();
        this.splitPane = splitPane;
        this.system = system;
        this.sender=account;
        this.parent=account.getParent();
        
         txtTestname.setText(testName);
    txtEnglish.setText(String.valueOf(english));
    txtMath.setText(String.valueOf(maths));
    txtFrench.setText(String.valueOf(french));
    txtSocial.setText(String.valueOf(social));
    txtScience.setText(String.valueOf(science));
    txtFeedback.setText(feedback);

    // Make the fields non-editable
    txtTestname.setEditable(false);
    txtEnglish.setEditable(false);
    txtMath.setEditable(false);
    txtFrench.setEditable(false);
    txtSocial.setEditable(false);
    txtScience.setEditable(false);
    txtFeedback.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        txtTestname = new javax.swing.JTextField();
        lblFrench = new javax.swing.JLabel();
        txtFrench = new javax.swing.JTextField();
        lblEnglish = new javax.swing.JLabel();
        txtEnglish = new javax.swing.JTextField();
        lblMath = new javax.swing.JLabel();
        txtMath = new javax.swing.JTextField();
        lblScience = new javax.swing.JLabel();
        txtScience = new javax.swing.JTextField();
        lblFeedback = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFeedback = new javax.swing.JTextArea();
        lblSocial = new javax.swing.JLabel();
        txtSocial = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        btnback.setBackground(new java.awt.Color(153, 153, 255));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View Test Wise");

        lblText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblText.setForeground(new java.awt.Color(255, 255, 255));
        lblText.setText("Test Name");

        txtTestname.setEditable(false);
        txtTestname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblFrench.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFrench.setForeground(new java.awt.Color(255, 255, 255));
        lblFrench.setText("French");

        txtFrench.setEditable(false);
        txtFrench.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrenchActionPerformed(evt);
            }
        });

        lblEnglish.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnglish.setForeground(new java.awt.Color(255, 255, 255));
        lblEnglish.setText("English");

        txtEnglish.setEditable(false);
        txtEnglish.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblMath.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMath.setForeground(new java.awt.Color(255, 255, 255));
        lblMath.setText("Math");

        txtMath.setEditable(false);
        txtMath.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblScience.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblScience.setForeground(new java.awt.Color(255, 255, 255));
        lblScience.setText("Science");

        txtScience.setEditable(false);
        txtScience.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblFeedback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFeedback.setForeground(new java.awt.Color(255, 255, 255));
        lblFeedback.setText("Feedback");

        txtFeedback.setEditable(false);
        txtFeedback.setColumns(20);
        txtFeedback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFeedback.setRows(5);
        jScrollPane1.setViewportView(txtFeedback);

        lblSocial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSocial.setForeground(new java.awt.Color(255, 255, 255));
        lblSocial.setText("Social");

        txtSocial.setEditable(false);
        txtSocial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(txtEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(txtFrench, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(txtMath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(txtScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(txtSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFeedback)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEnglish)
                                        .addComponent(lblFrench)
                                        .addComponent(lblMath)
                                        .addComponent(lblScience)
                                        .addComponent(lblSocial)
                                        .addComponent(lblText))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTestname, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEnglish, txtFrench, txtMath, txtScience, txtSocial, txtTestname});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblEnglish, lblFeedback, lblFrench, lblMath, lblScience, lblSocial, lblText});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnback)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblText)
                            .addComponent(txtTestname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEnglish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFrench)
                        .addGap(15, 15, 15)
                        .addComponent(lblMath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblScience)
                        .addGap(24, 24, 24)
                        .addComponent(lblSocial))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFrench, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFeedback))
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        StudentsAcademicProgress sap = new StudentsAcademicProgress(splitPane, sender, system, system);
        splitPane.setRightComponent(sap);

    }//GEN-LAST:event_btnbackActionPerformed

    private void txtFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFrenchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFrenchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnglish;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblFrench;
    private javax.swing.JLabel lblMath;
    private javax.swing.JLabel lblScience;
    private javax.swing.JLabel lblSocial;
    private javax.swing.JLabel lblText;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextArea txtFeedback;
    private javax.swing.JTextField txtFrench;
    private javax.swing.JTextField txtMath;
    private javax.swing.JTextField txtScience;
    private javax.swing.JTextField txtSocial;
    private javax.swing.JTextField txtTestname;
    // End of variables declaration//GEN-END:variables
}
