/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.DentalDoctorRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JSplitPane;

/**
 *
 * @author bbpri
 */
public class DentalDoctorWorkAreaJPanel extends javax.swing.JPanel {
    
    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;

    /**
     * Creates new form DentalDoctorWorkAreaJPanel
     */
    public DentalDoctorWorkAreaJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        this.account=account;
        this.organization=organization;
        this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoctorEnterprise = new javax.swing.JLabel();
        btnReview = new javax.swing.JButton();
        btnPrescribeTreatment = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblDoctorEnterprise.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblDoctorEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoctorEnterprise.setText("Doctor Enterprise");

        btnReview.setText("Review Health Data");

        btnPrescribeTreatment.setText("Prescribe Treatment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblDoctorEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnReview)
                    .addComponent(btnPrescribeTreatment))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblDoctorEnterprise)
                .addGap(87, 87, 87)
                .addComponent(btnReview, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnPrescribeTreatment)
                .addContainerGap(308, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrescribeTreatment;
    private javax.swing.JButton btnReview;
    private javax.swing.JLabel lblDoctorEnterprise;
    // End of variables declaration//GEN-END:variables
}
