/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.PsychiatristRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JSplitPane;
import ui.LoginScreen;

/**
 *
 * @author bbpri
 */
public class PsychiatristWorkAreaJPanel extends javax.swing.JPanel {
    
    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;

    /**
     * Creates new form PsychiatristWorkAreaJPanel
     */
    public PsychiatristWorkAreaJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        this.account=account;
        this.organization=organization;
        this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoctorEnterprise = new javax.swing.JLabel();
        btnReview = new javax.swing.JButton();
        btnPrescribeTreatment = new javax.swing.JButton();
        btnFeedback = new javax.swing.JButton();
        btnChatWithPsychiatrist = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblDoctorEnterprise.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblDoctorEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoctorEnterprise.setText("Psychiatrist Enterprise");

        btnReview.setBackground(new java.awt.Color(153, 153, 255));
        btnReview.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReview.setForeground(new java.awt.Color(255, 255, 255));
        btnReview.setText("Review Health Data");

        btnPrescribeTreatment.setBackground(new java.awt.Color(153, 153, 255));
        btnPrescribeTreatment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrescribeTreatment.setForeground(new java.awt.Color(255, 255, 255));
        btnPrescribeTreatment.setText("Prescribe Treatment");

        btnFeedback.setBackground(new java.awt.Color(153, 153, 255));
        btnFeedback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnFeedback.setText("Feedback");

        btnChatWithPsychiatrist.setBackground(new java.awt.Color(153, 153, 255));
        btnChatWithPsychiatrist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatWithPsychiatrist.setForeground(new java.awt.Color(255, 255, 255));
        btnChatWithPsychiatrist.setText("Chat with Teacher");
        btnChatWithPsychiatrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatWithPsychiatristActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 153, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblDoctorEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnReview)
                    .addComponent(btnPrescribeTreatment)
                    .addComponent(btnFeedback)
                    .addComponent(btnChatWithPsychiatrist, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorEnterprise)
                    .addComponent(btnLogout))
                .addGap(65, 65, 65)
                .addComponent(btnReview, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrescribeTreatment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChatWithPsychiatrist)
                .addContainerGap(279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChatWithPsychiatristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatWithPsychiatristActionPerformed
        // TODO add your handling code here:
        PsychiatristChatWithTeacherJPanel tcwp=new PsychiatristChatWithTeacherJPanel(splitPane, account, organization, system);
        splitPane.setRightComponent(tcwp);
    }//GEN-LAST:event_btnChatWithPsychiatristActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginScreen login=new LoginScreen(splitPane, system);
        splitPane.setRightComponent(login);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChatWithPsychiatrist;
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrescribeTreatment;
    private javax.swing.JButton btnReview;
    private javax.swing.JLabel lblDoctorEnterprise;
    // End of variables declaration//GEN-END:variables
}
