/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.TeacherRole;

import Business.Business.EcoSystem;
import Business.Business.Validation;
import Business.Organization.Organization;
import Business.Parent.Parent;
import Business.Roles.ParentRole;
import Business.Roles.StudentRole;
import Business.Roles.TeacherRole;
import Business.Student.Student;
import Business.Student.StudentDirectory;
import Business.UserAccount.UserAccount;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.validation.Validator;

/**
 *
 * @author bbpri
 */
public class RegisterJPanel extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;
    private ImageIcon finalImg;

    /**
     * Creates new form RegisterJPanel
     */
    public RegisterJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane = splitPane;
        this.account = account;
        this.organization = organization;
        this.system = system;
        populateGenderComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        lblEmail = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtPName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPNo = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        Gender = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnBrowseImage = new javax.swing.JButton();
        lblEmail2 = new javax.swing.JLabel();
        txtHt = new javax.swing.JTextField();
        lblEmail3 = new javax.swing.JLabel();
        txtWt = new javax.swing.JTextField();
        lblEmail4 = new javax.swing.JLabel();
        lblEmail5 = new javax.swing.JLabel();
        lblEmail6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        cmbGender = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register Students");

        txtPwd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Age");

        btnRegister.setBackground(new java.awt.Color(153, 153, 255));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        lblPassword1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword1.setText("Password");

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("Username");

        txtPName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Parent Name");

        txtPNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblEmail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail1.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail1.setText("Phone no");

        txtAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Gender.setForeground(new java.awt.Color(255, 255, 255));
        Gender.setText("Gender");

        btnback.setBackground(new java.awt.Color(153, 153, 255));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lblImage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblImage.setForeground(new java.awt.Color(255, 255, 255));
        lblImage.setText("<No Image>");

        btnBrowseImage.setBackground(new java.awt.Color(153, 153, 255));
        btnBrowseImage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBrowseImage.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowseImage.setText("Browse Image");
        btnBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseImageActionPerformed(evt);
            }
        });

        lblEmail2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail2.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail2.setText("Height ");

        txtHt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblEmail3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail3.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail3.setText("Weight ");

        txtWt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblEmail4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail4.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail4.setText("in meter");

        lblEmail5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail5.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail5.setText("in kgs");

        lblEmail6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail6.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail6.setText("Parents Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Will be same as Name entered");

        btnRemove.setBackground(new java.awt.Color(153, 153, 255));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        cmbGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(btnRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail6)
                    .addComponent(lblEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblPassword1)
                    .addComponent(lblUserName)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender)
                    .addComponent(lblEmail1))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHt)
                    .addComponent(txtName)
                    .addComponent(txtAge)
                    .addComponent(txtPwd)
                    .addComponent(txtPName)
                    .addComponent(txtPNo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWt)
                    .addComponent(txtEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnRemove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBrowseImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnback))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmail4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail5)
                            .addComponent(txtWt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserName)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword1)
                            .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail1)
                            .addComponent(txtPNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail2)
                            .addComponent(txtHt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmail3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrowseImage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove))
                .addGap(31, 31, 31)
                .addComponent(btnRegister)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        lblImage.setIcon(null);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        // TODO add your handling code here:
//        cmbGender.removeAllItems();
//        cmbGender.addItem("Female");
//        cmbGender.addItem("Male");
    }//GEN-LAST:event_cmbGenderActionPerformed

    private void populateGenderComboBox() {
        cmbGender.removeAllItems();
        cmbGender.addItem("Female");
        cmbGender.addItem("Male");
    }

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtUserNameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:

        String name = txtName.getText();
        // int age = Integer.parseInt(txtAge.getText());
        String ageText = txtAge.getText();
        String gender = (String)cmbGender.getSelectedItem();
        String username = txtName.getText();
        String password = String.valueOf(txtPwd.getPassword());

        String phno = txtPNo.getText();
        String Parentname = txtPName.getText();
        String parentUsername = Parentname + "_" + name;
        String parentPassword = "defPwd";
        String heightText = txtHt.getText();
        String weightText = txtWt.getText();
        String  email = txtEmail.getText();

        // Validate all fields
        if (!Validation.validateNotEmpty(name, "Name") || !Validation.validateName(name)) {
            return;
        }

        if (!Validation.validateNotEmpty(ageText, "Age") || !Validation.validateAge(ageText)) {
            return;
        }

        if (!Validation.validateNotEmpty(gender, "Gender")) {
            return;
        }

        // if (!Validation.validateNotEmpty(username, "Username") ||
        // !Validation.validateUsername(username)) {
        // return;
        // }

        if (!Validation.validatePassword(password)) {
            return;
        }
        
        if (!Validation.validateNotEmpty(phno, "Phone Number") || !Validation.validatePhoneNumber(phno)) {
            return;
        }

        if (!Validation.validateNotEmpty(Parentname, "Parent Name") || !Validation.validateName(Parentname)) {
            return;
        }

        if (!Validation.validateNotEmpty(heightText, "Height") || !Validation.validateHeight(heightText)) {
            return;
        }

        if (!Validation.validateNotEmpty(weightText, "Weight") || !Validation.validateWeight(weightText)) {
            return;
        }

        if (!Validation.validateNotEmpty(email, "Email") || !Validation.validateEmail(email)) {
            return;
        }

        if (system.getUserAccountDirectory().checkIfUsernameExists(username)) {
            System.out.println("Username already exists: " + username);
            JOptionPane.showMessageDialog(null, "Student username already exists. Please choose a different username.",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (system.getUserAccountDirectory().checkIfUsernameExists(parentUsername)) {
            System.out.println("Parent username already exists: " + parentUsername);
            JOptionPane.showMessageDialog(null,
                    "Parent username already exists. Please choose a different parent name.", "Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int age = Integer.parseInt(ageText);
        double height = Double.parseDouble(heightText);
        double weight = Double.parseDouble(weightText);

        // Find existing parent account or create a new one
        Parent parent = null;
        UserAccount parentAccount = organization.getUserAccountDirectory().getUserAccountByUsername(parentUsername);
        if (parentAccount != null) {
            if (parentAccount.getRole() instanceof ParentRole) {
                parent = parentAccount.getParent();
                System.out.println("Existing parent account found for: " + parent.getName());
            } else {
                JOptionPane.showMessageDialog(null,
                        "Error: Parent username already exists but is not assigned ParentRole.", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            parent = new Parent(Parentname, phno);
            parentAccount = organization.getUserAccountDirectory().createUserAccount(parentUsername, parentPassword,
                    new ParentRole());
            parentAccount.setParent(parent);
            System.out.println("Parent account created for: " + Parentname);
        }

        // Check if the student already exists in the directory
        Organization studentOrganization = system.getOrganizationDirectory()
                .findOrganization(Organization.Type.Student);
        if (studentOrganization == null) {
            studentOrganization = system.getOrganizationDirectory().createOrganization(Organization.Type.Student,
                    "Student");
        }

        StudentDirectory studentList = studentOrganization.getStudentDirectory();
        Student existingStudent = studentList.findStudentByName(name);
        if (existingStudent != null) {
            JOptionPane.showMessageDialog(null,
                    "A student with this username and name already exists. Please use a different username and name.",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Create new student and associate with parent
        Student student = studentList.createStudent(name, age, gender, Parentname, phno, height, weight,email);
        student.setLogoImage(finalImg);
        student.setParent(parent);
        parent.addStudent(student);

        UserAccount studentAccount = organization.getUserAccountDirectory().createUserAccount(username, password,
                new StudentRole());
        studentAccount.setStudent(student);

        System.out.println("Student account created for: " + name);

        // Register student to grade if teacher role
        if (account.getRole() instanceof TeacherRole) {
            TeacherRole teacherRole = (TeacherRole) account.getRole();
            teacherRole.registerStudent(student, "Grade 5");
            System.out.println("Student " + student.getName() + " registered in grade " + student.getGrade());
        } else {
            System.out.println("User is not assigned a TeacherRole.");
        }

        JOptionPane.showMessageDialog(this, "Student Registered successfully!");

        // Reset input fields
        txtName.setText("");
        txtAge.setText("");
        txtPwd.setText("");
//        txtUserName.setText("");
        txtPNo.setText("");
        txtPName.setText("");
        txtHt.setText("");
        txtWt.setText("");
        txtEmail.setText("");
        lblImage.setIcon(null);

    }// GEN-LAST:event_btnRegisterActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        TeacherWorkAreaJPanel pwajp = new TeacherWorkAreaJPanel(splitPane, account, system, system);
        splitPane.setRightComponent(pwajp);
    }// GEN-LAST:event_btnbackActionPerformed

    private void btnBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBrowseImageActionPerformed
        JFileChooser browseImageFile = new JFileChooser();
        // Filter image extensions of the upload picture.
        FileNameExtensionFilter filefilter = new FileNameExtensionFilter("IMAGES", "jpeg", "png", "jpg");
        browseImageFile.addChoosableFileFilter(filefilter);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, "Logo fetched and added successfully!");
            // Display image on jlable
            ImageIcon imgi = new ImageIcon(selectedImagePath);
            // Resize image to fit jlabel
            Image image = imgi.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(),
                    Image.SCALE_SMOOTH);
            this.finalImg = new ImageIcon(image);
            lblImage.setIcon(finalImg);

        } // TODO add your handling code here:
    }// GEN-LAST:event_btnBrowseImageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gender;
    private javax.swing.JButton btnBrowseImage;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEmail3;
    private javax.swing.JLabel lblEmail4;
    private javax.swing.JLabel lblEmail5;
    private javax.swing.JLabel lblEmail6;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHt;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtPNo;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtWt;
    // End of variables declaration//GEN-END:variables
}
