/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.TeacherRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Roles.StudentRole;
import Business.Roles.TeacherRole;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bbpri
 */
public class StudentHealthRecordPanel extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;

    /**
     * Creates new form StudentHealthRecordPanel
     */
    public StudentHealthRecordPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane = splitPane;
        this.account = account;
        this.organization = organization;
        this.system = system;

        populateStudentComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHealthRecords = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbStudents = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cbHep = new javax.swing.JCheckBox();
        cbPolio = new javax.swing.JCheckBox();
        cbMeas = new javax.swing.JCheckBox();
        btnSubmit1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        btnback1.setBackground(new java.awt.Color(153, 153, 255));
        btnback1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Health Records");

        tblHealthRecords.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblHealthRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Name", "Hepatitis", "Measles", "Polio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHealthRecords);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Immunizations:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Student to Update Record");

        cmbStudents.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbStudents.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStudentsActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("check if the selected student is immunized with the following vaccines:");

        cbHep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbHep.setForeground(new java.awt.Color(255, 255, 255));
        cbHep.setText("Hepatitis");

        cbPolio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbPolio.setForeground(new java.awt.Color(255, 255, 255));
        cbPolio.setText("Polio");

        cbMeas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbMeas.setForeground(new java.awt.Color(255, 255, 255));
        cbMeas.setText("Measels");
        cbMeas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMeasActionPerformed(evt);
            }
        });

        btnSubmit1.setBackground(new java.awt.Color(153, 153, 255));
        btnSubmit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmit1.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit1.setText("Update");
        btnSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnback1)
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(cbHep)
                    .addComponent(cbPolio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbMeas)
                        .addGap(102, 102, 102)
                        .addComponent(btnSubmit1)))
                .addGap(0, 118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addComponent(btnback1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbHep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMeas)
                    .addComponent(btnSubmit1))
                .addGap(5, 5, 5)
                .addComponent(cbPolio)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        TeacherWorkAreaJPanel nwajp = new TeacherWorkAreaJPanel(splitPane, account, system, system);
        splitPane.setRightComponent(nwajp);
    }//GEN-LAST:event_btnback1ActionPerformed

    private void cmbStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStudentsActionPerformed
        // TODO add your handling code here:
        Student selectedStudent = (Student) cmbStudents.getSelectedItem();
        if (selectedStudent != null) {
            cbHep.setSelected(selectedStudent.getImmunizationStatus("Hepatitis"));
            cbMeas.setSelected(selectedStudent.getImmunizationStatus("Measles"));
            cbPolio.setSelected(selectedStudent.getImmunizationStatus("Polio"));
        }
        populateHealthRecordsTable(selectedStudent);
    }//GEN-LAST:event_cmbStudentsActionPerformed

    private void cbMeasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMeasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMeasActionPerformed

    private void btnSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit1ActionPerformed
        // TODO add your handling code here:
        Student selectedStudent = (Student) cmbStudents.getSelectedItem();

        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(this, "Please select a student.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        selectedStudent.updateImmunization("Hepatitis", cbHep.isSelected());
        selectedStudent.updateImmunization("Measles", cbMeas.isSelected());
        selectedStudent.updateImmunization("Polio", cbPolio.isSelected());

        JOptionPane.showMessageDialog(this, "Health records updated successfully!");
        populateHealthRecordsTable(selectedStudent);

    }//GEN-LAST:event_btnSubmit1ActionPerformed

    private void populateStudentComboBox() {
        cmbStudents.removeAllItems();
        Organization org = system.getOrganizationDirectory().findOrganization(Organization.Type.Student);
        org.getStudentDirectory().getStudentList();
        System.out.println("Student List is as follows ");
        for (Student s : org.getStudentDirectory().getStudentList()) {
            System.out.println(s);
            cmbStudents.addItem(s);
        }
    }

    private void populateHealthRecordsTable(Student selectedStudent) {
        DefaultTableModel model = (DefaultTableModel) tblHealthRecords.getModel();
        model.setRowCount(0);
        
        Organization org = system.getOrganizationDirectory().findOrganization(Organization.Type.Student);
        ArrayList<Student> studentlist = org.getStudentDirectory().getStudentList(); 
        if(studentlist.isEmpty()){
            JOptionPane.showMessageDialog(null, "No students are found!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        for (Student student : studentlist) {
            // If a specific student is selected, filter by that student
            if (student != null && !student.equals(selectedStudent)) {
                continue;
            }
            
             Object[] row = {
                student.getName(),
                student.getImmunizationStatus("Hepatitis"),
                student.getImmunizationStatus("Measles"),
                student.getImmunizationStatus("Polio")
            };
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit1;
    private javax.swing.JButton btnback1;
    private javax.swing.JCheckBox cbHep;
    private javax.swing.JCheckBox cbMeas;
    private javax.swing.JCheckBox cbPolio;
    private javax.swing.JComboBox cmbStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHealthRecords;
    // End of variables declaration//GEN-END:variables
}
