/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.TeacherRole;

import Business.Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.EnterpriseNetwork;
import Business.Organization.Organization;
import Business.Organization.PsychiatristOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PsychiatristChatWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bbpri
 */
public class TeacherChatWithPsychiatrist extends javax.swing.JPanel {
     private JSplitPane splitPane;
    private UserAccount account;
     private UserAccount sender;
    private Organization organization;
    private EcoSystem system;
    // private Image originalImage1;
    private Image originalImage2;
    private Image originalImage3;


    /**
     * Creates new form TeacherChatWithPsychiatrist
     */
    public TeacherChatWithPsychiatrist(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        this.sender=account;
        this.organization=organization;
        this.system=system;
        populateRequestTable();
        try {
           // URL imageURL1 = getClass().getResource("/images/teacher.jpg");
            URL imageURL2 = getClass().getResource("/images/female-chat.png");
            URL imageURL3 = getClass().getResource("/images/Office-Client-Male-Light-icon.png");
//            if (imageURL1 != null) {
//                originalImage1 = ImageIO.read(imageURL1);
//                System.out.println("Image 1 found");
//            } else {
//                System.err.println("Image1 not found");
//            }
            if (imageURL2 != null) {

                originalImage2 = ImageIO.read(imageURL2);
                System.out.println("Image 2 found");
            } else {
                System.err.println("Image2 not found");
            }
            if (imageURL3 != null) {
                originalImage3 = ImageIO.read(imageURL3);
                System.out.println("Image 3 found");
            } else {
                System.err.println("Image3 not found");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblparent1 = new javax.swing.JLabel();
        btnback1 = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPMessage = new javax.swing.JTextArea();
        lblTitle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChatHistory = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        txtTeacher = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        lblparent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Office-Client-Male-Light-icon.png"))); // NOI18N

        btnback1.setBackground(new java.awt.Color(153, 153, 255));
        btnback1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        btnSend.setBackground(new java.awt.Color(153, 153, 255));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(153, 153, 255));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtStatus.setBackground(new java.awt.Color(153, 153, 255));
        txtStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 255, 255));
        txtStatus.setText("Pending");

        txtPMessage.setColumns(20);
        txtPMessage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPMessage.setRows(5);
        jScrollPane1.setViewportView(txtPMessage);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Chat with Psychiatrist");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/female-chat.png"))); // NOI18N

        tblChatHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblChatHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Recipient", "Status", "Reply"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblChatHistory);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Psychiatrist");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Chat History");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnback1)
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnSend)
                                        .addComponent(jLabel5)))
                                .addComponent(lblTitle)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(lblparent1)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(233, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitle)
                        .addComponent(btnback1))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSend))))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(lblparent1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(224, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        TeacherWorkAreaJPanel twajp=new TeacherWorkAreaJPanel(splitPane, account, organization, system);
        splitPane.setRightComponent(twajp);
    }//GEN-LAST:event_btnback1ActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:

        String reqMessage = txtPMessage.getText();
        if (reqMessage.equals("") || reqMessage.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a message to send.");
            return;
        }

        PsychiatristChatWorkRequest message = new PsychiatristChatWorkRequest();
        message.setMessage(reqMessage);
        message.setSender(sender);
        // message.setReceiver("");
        message.setStatus("Sent");
        // Use the `selectedTeacher` object to send your message
        //        message.setReceiver(cmbTeacher.getSelectedItem());
        txtStatus.setText("Sent");

        Organization orgn = null;
        for (EnterpriseNetwork network : system.getNetworkList()) {            
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof PsychiatristOrganization) {
                        orgn = organization;
                        break;
                    }
                }
            }
        }

        System.out.println("Whats the organization " + orgn);
        if (orgn != null) {
            orgn.getWorkQueue().getWorkRequestPsychiatrist().add(message);
            System.out.println("inside send button " + orgn.getWorkQueue().getWorkRequestPsychiatrist().get(0));
            sender.getWorkQueue().getWorkRequestPsychiatrist().add(message);
        }

        JOptionPane.showMessageDialog(null, "Request message sent", "Information", JOptionPane.INFORMATION_MESSAGE);
        populateRequestTable();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:

        populateRequestTable();
        int size = sender.getWorkQueue().getWorkRequestPsychiatrist().size();
        WorkRequest result = sender.getWorkQueue().getWorkRequestPsychiatrist().get(size - 1);
    }//GEN-LAST:event_btnRefreshActionPerformed


     public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblChatHistory.getModel();
        System.out.println("Hello inside table" + sender.getWorkQueue().getWorkRequestPsychiatrist());
        model.setRowCount(0);
        for (WorkRequest request : sender.getWorkQueue().getWorkRequestPsychiatrist()) {
            System.out.println("Hello from table" + request.getMessage());
            Object[] row = new Object[4];
            row[0] = request.getMessage();
//          cmbTeacher.getSelectedItem();
//            row[1] = cmbTeacher.getSelectedItem();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            String result = ((PsychiatristChatWorkRequest) request).getResultMessage();
            row[3] = result == null ? "Waiting" : result;

            model.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnback1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblparent1;
    private javax.swing.JTable tblChatHistory;
    private javax.swing.JTextArea txtPMessage;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTeacher;
    // End of variables declaration//GEN-END:variables
}
