/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.TeacherRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JSplitPane;
import ui.LoginScreen;

/**
 *
 * @author bbpri
 */
public class TeacherWorkAreaJPanel extends javax.swing.JPanel {
    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;

    /**
     * Creates new form TeacherWorkAreaJPanel
     */
    public TeacherWorkAreaJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        this.account=account;
        this.organization=organization;
        this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegisterStudents = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnChatWithParents = new javax.swing.JButton();
        btnChatWithParents1 = new javax.swing.JButton();
        btnChatWithParents2 = new javax.swing.JButton();
        btnChatWithPsychiatrist = new javax.swing.JButton();
        btnEmergencyRequest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        btnRegisterStudents.setBackground(new java.awt.Color(153, 153, 255));
        btnRegisterStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterStudents.setText("Register Students");
        btnRegisterStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterStudentsActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 153, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnChatWithParents.setBackground(new java.awt.Color(153, 153, 255));
        btnChatWithParents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatWithParents.setForeground(new java.awt.Color(255, 255, 255));
        btnChatWithParents.setText("Chat with Parents");
        btnChatWithParents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatWithParentsActionPerformed(evt);
            }
        });

        btnChatWithParents1.setBackground(new java.awt.Color(153, 153, 255));
        btnChatWithParents1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatWithParents1.setForeground(new java.awt.Color(255, 255, 255));
        btnChatWithParents1.setText("Update Student Records");
        btnChatWithParents1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatWithParents1ActionPerformed(evt);
            }
        });

        btnChatWithParents2.setBackground(new java.awt.Color(153, 153, 255));
        btnChatWithParents2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatWithParents2.setForeground(new java.awt.Color(255, 255, 255));
        btnChatWithParents2.setText("Student Health Records");
        btnChatWithParents2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatWithParents2ActionPerformed(evt);
            }
        });

        btnChatWithPsychiatrist.setBackground(new java.awt.Color(153, 153, 255));
        btnChatWithPsychiatrist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChatWithPsychiatrist.setForeground(new java.awt.Color(255, 255, 255));
        btnChatWithPsychiatrist.setText("Chat with Psychiatrist");
        btnChatWithPsychiatrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatWithPsychiatristActionPerformed(evt);
            }
        });

        btnEmergencyRequest.setBackground(new java.awt.Color(153, 153, 255));
        btnEmergencyRequest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmergencyRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnEmergencyRequest.setText("Emergency Request");
        btnEmergencyRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmergencyRequestActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Teacher's Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChatWithParents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegisterStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(btnChatWithParents1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChatWithParents2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChatWithPsychiatrist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmergencyRequest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(413, 413, 413))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addComponent(btnRegisterStudents)
                .addGap(18, 18, 18)
                .addComponent(btnChatWithParents)
                .addGap(18, 18, 18)
                .addComponent(btnChatWithParents1)
                .addGap(18, 18, 18)
                .addComponent(btnChatWithParents2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChatWithPsychiatrist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmergencyRequest)
                .addContainerGap(278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterStudentsActionPerformed
        // TODO add your handling code here:
        RegisterJPanel rjp=new RegisterJPanel(splitPane, account, organization, system);
        splitPane.setRightComponent(rjp);
    }//GEN-LAST:event_btnRegisterStudentsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginScreen login=new LoginScreen(splitPane, system);
        splitPane.setRightComponent(login);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnChatWithParentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatWithParentsActionPerformed
        // TODO add your handling code here:
        TeacherChatWithParent rjp=new TeacherChatWithParent(splitPane, account, organization, system);
        splitPane.setRightComponent(rjp);
    }//GEN-LAST:event_btnChatWithParentsActionPerformed

    private void btnChatWithParents1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatWithParents1ActionPerformed
        // TODO add your handling code here:
        UpdateStudentAcademicProgressJPanel rjp=new UpdateStudentAcademicProgressJPanel(splitPane, account, organization, system);
        splitPane.setRightComponent(rjp);
    }//GEN-LAST:event_btnChatWithParents1ActionPerformed

    private void btnChatWithParents2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatWithParents2ActionPerformed
        // TODO add your handling code here:
        StudentHealthRecordPanel rjp=new StudentHealthRecordPanel(splitPane, account, organization, system);
        splitPane.setRightComponent(rjp);
    }//GEN-LAST:event_btnChatWithParents2ActionPerformed

    private void btnChatWithPsychiatristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatWithPsychiatristActionPerformed
        // TODO add your handling code here:
        TeacherChatWithPsychiatrist tcwp=new TeacherChatWithPsychiatrist(splitPane, account, organization, system);
        splitPane.setRightComponent(tcwp);
    }//GEN-LAST:event_btnChatWithPsychiatristActionPerformed

    private void btnEmergencyRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergencyRequestActionPerformed
        // TODO add your handling code here:
        EmergencyRequestJPanel erjp=new EmergencyRequestJPanel(splitPane, account, organization, system);
        splitPane.setRightComponent(erjp);
    }//GEN-LAST:event_btnEmergencyRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChatWithParents;
    private javax.swing.JButton btnChatWithParents1;
    private javax.swing.JButton btnChatWithParents2;
    private javax.swing.JButton btnChatWithPsychiatrist;
    private javax.swing.JButton btnEmergencyRequest;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegisterStudents;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
