/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.TeacherRole;

import Business.Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.TeacherOrganization;
import Business.Roles.StudentRole;
import Business.Roles.TeacherRole;
import Business.Student.Student;
import Business.Student.StudentDirectory;
import Business.UserAccount.UserAccount;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.util.ArrayList;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author bbpri
 */
public class UpdateStudentAcademicProgressJPanel extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;
    Organization teacherOrg;

    /**
     * Creates new form UpdateStudentAcademicProgressJPanel
     */
    public UpdateStudentAcademicProgressJPanel(JSplitPane splitPane, UserAccount account, Organization organization,
            EcoSystem system) {
        initComponents();
        this.splitPane = splitPane;
        this.account = account;
        this.organization = organization;
        this.system = system;

        populateStudentComboBox();
        populateTestComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnback1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbStudents = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbTests = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtEng = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMarks = new javax.swing.JTable();
        txtMaths = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFrench = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSocial = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtScience = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaFeedback = new javax.swing.JTextArea();
        btnDownload = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update Student Records");

        btnback1.setBackground(new java.awt.Color(153, 153, 255));
        btnback1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Student to Update Marks");

        cmbStudents.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbStudents.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStudentsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Test");

        cmbTests.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbTests.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("English");

        txtEng.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEngActionPerformed(evt);
            }
        });

        tblMarks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblMarks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Test Name", "English", "Maths", "French", "Social", "Science"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMarks);
        if (tblMarks.getColumnModel().getColumnCount() > 0) {
            tblMarks.getColumnModel().getColumn(6).setResizable(false);
        }

        txtMaths.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMathsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Maths");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Marks for Below Subjects");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("French");

        txtFrench.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrenchActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Social");

        txtSocial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Science");

        txtScience.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtScience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScienceActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(153, 153, 255));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblFeedback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFeedback.setForeground(new java.awt.Color(255, 255, 255));
        lblFeedback.setText("Feedback");

        txtareaFeedback.setColumns(20);
        txtareaFeedback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtareaFeedback.setRows(5);
        jScrollPane2.setViewportView(txtareaFeedback);

        btnDownload.setBackground(new java.awt.Color(153, 153, 255));
        btnDownload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDownload.setForeground(new java.awt.Color(255, 255, 255));
        btnDownload.setText("Download Pdf");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnback1)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbTests, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFeedback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtEng, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaths, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(32, 32, 32)
                                            .addComponent(txtSocial))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtScience, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtFrench, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnSubmit))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDownload)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addComponent(btnback1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbTests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtEng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFrench, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(btnSubmit))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFeedback))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDownload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblMarks.getModel();

        String path = "";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int selection = fileChooser.showSaveDialog(this);
    
        if (selection == JFileChooser.APPROVE_OPTION) {
            path = fileChooser.getSelectedFile().getPath();
        } else {
            JOptionPane.showMessageDialog(this, "Export canceled.");
            return; 
        }
    
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(path + "/StudentMarksReport.pdf"));
            document.open();
    
            PdfPTable pdfTable = new PdfPTable(model.getColumnCount());
    
            for (int col = 0; col < model.getColumnCount(); col++) {
                pdfTable.addCell(model.getColumnName(col));
            }
    
            for (int row = 0; row < model.getRowCount(); row++) {
                for (int col = 0; col < model.getColumnCount(); col++) {
                    Object cellValue = model.getValueAt(row, col);
                    pdfTable.addCell(cellValue != null ? cellValue.toString() : "");
                }
            }
    
            document.add(pdfTable);
    
            JOptionPane.showMessageDialog(this, "PDF downloaded successfully at " + path);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error generating PDF: " + e.getMessage());
        } finally {
            document.close();
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        TeacherWorkAreaJPanel nwajp = new TeacherWorkAreaJPanel(splitPane, account, system, system);
        splitPane.setRightComponent(nwajp);
    }// GEN-LAST:event_btnback1ActionPerformed

    private void txtEngActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtEngActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtEngActionPerformed

    private void txtFrenchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFrenchActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtFrenchActionPerformed

    private void txtScienceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtScienceActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtScienceActionPerformed

    private void cmbStudentsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbStudentsActionPerformed
        // TODO add your handling code here:
        Student selectedStudent = (Student) cmbStudents.getSelectedItem();

        if (selectedStudent != null) {
            populateMarksTable(selectedStudent);
        }
    }// GEN-LAST:event_cmbStudentsActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        try {
            Student selectedStudent = (Student) cmbStudents.getSelectedItem();
            String selectedTest = (String) cmbTests.getSelectedItem();

            if (selectedStudent == null || selectedTest == null) {
                JOptionPane.showMessageDialog(null, "Please select a student and a test.");
                return;
            }

            // Validate that none of the fields are empty
            if (txtMaths.getText().isEmpty() || txtEng.getText().isEmpty() || txtScience.getText().isEmpty()
                    || txtSocial.getText().isEmpty() || txtFrench.getText().isEmpty() || txtareaFeedback.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please ensure all fields are filled.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int mathsMarks, englishMarks, scienceMarks, socialMarks, frenchMarks;

            // Validate numeric input for marks
            try {
                mathsMarks = Integer.parseInt(txtMaths.getText());
                englishMarks = Integer.parseInt(txtEng.getText());
                scienceMarks = Integer.parseInt(txtScience.getText());
                socialMarks = Integer.parseInt(txtSocial.getText());
                frenchMarks = Integer.parseInt(txtFrench.getText());
                // Check range
                if (mathsMarks < 1 || mathsMarks > 100 || englishMarks < 1 || englishMarks > 100
                        || scienceMarks < 1 || scienceMarks > 100 || socialMarks < 1 || socialMarks > 100
                        || frenchMarks < 1 || frenchMarks > 100) {
                    JOptionPane.showMessageDialog(this, "Marks should be within the range of 1 to 100.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter valid numeric values for all marks fields.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Map<String, Integer> marks = new HashMap<>();
            marks.put("Maths", Integer.parseInt(txtMaths.getText()));
            marks.put("English", Integer.parseInt(txtEng.getText()));
            marks.put("Science", Integer.parseInt(txtScience.getText()));
            marks.put("Social", Integer.parseInt(txtSocial.getText()));
            marks.put("French", Integer.parseInt(txtFrench.getText()));

            String feedback = txtareaFeedback.getText();

            if (account.getRole() instanceof TeacherRole) {
                TeacherRole teacherRole = (TeacherRole) account.getRole();
                teacherRole.updateStudentMarks(selectedStudent, selectedTest, marks);
                selectedStudent.setFeedbackTest(selectedTest, feedback);
                JOptionPane.showMessageDialog(this, "Marks updated successfully!");
                populateMarksTable(selectedStudent);
            } else {
                JOptionPane.showMessageDialog(this, "Error: You do not have permission to update marks.");
            }

            String subject = "Student Progress Update";
            String message = "Dear Parent, \n\nYour child's updated marks are now available in the system. Please log in to view them.\n\nBest regards,\nSchool Administration";
            //String parentEmail = "bpriyanka153@gmail.com";

            EmailUtility.sendEmail(selectedStudent.getParentemail(), subject, message);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred while updating marks: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        txtMaths.setText("");
        txtEng.setText("");
        txtSocial.setText("");
        txtScience.setText("");
        txtFrench.setText("");
        txtareaFeedback.setText("");
        

//        String parentEmail = "bpriyanka153@gmail.com";
    }// GEN-LAST:event_btnSubmitActionPerformed

    private void populateMarksTable(Student selectedstudent) {
        DefaultTableModel model = (DefaultTableModel) tblMarks.getModel();
        model.setRowCount(0);

        Organization org = system.getOrganizationDirectory().findOrganization(Organization.Type.Student);
        ArrayList<Student> studentlist = org.getStudentDirectory().getStudentList();
        if (studentlist.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No students are found !", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (Student student : studentlist) {
            // If a specific student is selected, filter by that student
            if (student != null && !student.equals(selectedstudent)) {
                continue;
            }

            // Iterate through the test marks of the student
            for (String testName : student.getTestMarks().keySet()) {
                Map<String, Integer> marks = student.getMarksForTest(testName);

                // Retrieve subject marks
                int englishMarks = marks.getOrDefault("English", 0);
                int mathsMarks = marks.getOrDefault("Maths", 0);
                int frenchMarks = marks.getOrDefault("French", 0);
                int socialMarks = marks.getOrDefault("Social", 0);
                int scienceMarks = marks.getOrDefault("Science", 0);
                String feedback = student.getFeedbackTest(testName);

                // Add a new row for each test
                Object[] row = new Object[]{
                    student.getName(), // Student Name
                    testName, // Test Name
                    englishMarks, // English Marks
                    mathsMarks, // Maths Marks
                    frenchMarks, // French Marks
                    socialMarks, // Social Marks
                    scienceMarks,
                    feedback// Science Marks
                };
                model.addRow(row);
            }
        }
    }

    private void txtMathsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMathsActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtMathsActionPerformed

    // populate students in combo box
    private void populateStudentComboBox() {
        cmbStudents.removeAllItems();
        Organization org = system.getOrganizationDirectory().findOrganization(Organization.Type.Student);
        org.getStudentDirectory().getStudentList();
        System.out.println("Student List is as follows ");
        for (Student s : org.getStudentDirectory().getStudentList()) {
            System.out.println(s);
            cmbStudents.addItem(s);
        }

        populateMarksTable((Student) cmbStudents.getSelectedItem());
    }

    // populate tests in combo box
    private void populateTestComboBox() {
        cmbTests.removeAllItems();
        cmbTests.addItem("Unit Test 1");
        cmbTests.addItem("Unit Test 2");
        cmbTests.addItem("Midterm");
        cmbTests.addItem("Final Exam");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnback1;
    private javax.swing.JComboBox cmbStudents;
    private javax.swing.JComboBox cmbTests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JTable tblMarks;
    private javax.swing.JTextField txtEng;
    private javax.swing.JTextField txtFrench;
    private javax.swing.JTextField txtMaths;
    private javax.swing.JTextField txtScience;
    private javax.swing.JTextField txtSocial;
    private javax.swing.JTextArea txtareaFeedback;
    // End of variables declaration//GEN-END:variables

}
