/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.SportsCoachRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanaabena
 */
/**
 * Creates new form CollaborateWithHealthcareJPanel
 */
public class RecordPerformanceJPanel extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;
    private Student student;

    /**
     * Creates new form RecordPerformanceJPanel
     */
    public RecordPerformanceJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane = splitPane;
        this.account = account;
        this.organization = organization;
        this.system = system;
//        populateStudentDetails();

        populateStudentComboBox();
        populatePerformanceComboBox();
    }

    //populate students in combo box
    private void populateStudentComboBox() {
        cmbStudents.removeAllItems();
        Organization org = system.getOrganizationDirectory().findOrganization(Organization.Type.Student);
        org.getStudentDirectory().getStudentList();
        for (Student s : org.getStudentDirectory().getStudentList()) {
            cmbStudents.addItem(s);
        }

        populatePerformanceTable2((Student) cmbStudents.getSelectedItem());
    }

    //populate tests in combo box
    private void populatePerformanceComboBox() {
        cmbGamePlayed.removeAllItems();
        cmbGamePlayed.addItem("Basketball");
        cmbGamePlayed.addItem("Soccer");
        cmbGamePlayed.addItem("Football");
        cmbGamePlayed.addItem("Baseball");
        cmbGamePlayed.addItem("Cricket");
    }

//    private void populateStudentDetails() {
//        if (student != null) {
//            txtStudentName.setText(student.getName());
//        } else {
//            JOptionPane.showMessageDialog(this, "No student data available!");
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        btnBack = new javax.swing.JButton();
        lblStudentName = new javax.swing.JLabel();
        lblGamePlayed = new javax.swing.JLabel();
        lblRecordPerformance = new javax.swing.JLabel();
        cmbGamePlayed = new javax.swing.JComboBox<>();
        cmbSpeed = new javax.swing.JComboBox<>();
        lblSpeed = new javax.swing.JLabel();
        cmbStrength = new javax.swing.JComboBox<>();
        lblStrength = new javax.swing.JLabel();
        lblEndurance = new javax.swing.JLabel();
        cmbEndurance = new javax.swing.JComboBox<>();
        cmbMentalFocus = new javax.swing.JComboBox<>();
        lblMentalFocus = new javax.swing.JLabel();
        lblPerformanceScore = new javax.swing.JLabel();
        sliderPerformanceScore = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPerformance = new javax.swing.JTable();
        cmbStudents = new javax.swing.JComboBox();
        btnRecord = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblStudentName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentName.setText("Student's Name:");

        lblGamePlayed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGamePlayed.setForeground(new java.awt.Color(255, 255, 255));
        lblGamePlayed.setText("Game Played:");

        lblRecordPerformance.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblRecordPerformance.setForeground(new java.awt.Color(255, 255, 255));
        lblRecordPerformance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecordPerformance.setText("Record Performance");

        cmbGamePlayed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbGamePlayed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soccer", "Basketball", "Football", "Baseball", "Cricket" }));
        cmbGamePlayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGamePlayedActionPerformed(evt);
            }
        });

        cmbSpeed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Good", "Average", "Poor" }));
        cmbSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSpeedActionPerformed(evt);
            }
        });

        lblSpeed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSpeed.setForeground(new java.awt.Color(255, 255, 255));
        lblSpeed.setText("Speed:");

        cmbStrength.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbStrength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Good", "Average", "Poor" }));
        cmbStrength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStrengthActionPerformed(evt);
            }
        });

        lblStrength.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStrength.setForeground(new java.awt.Color(255, 255, 255));
        lblStrength.setText("Strength:");

        lblEndurance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEndurance.setForeground(new java.awt.Color(255, 255, 255));
        lblEndurance.setText("Endurance:");

        cmbEndurance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbEndurance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Good", "Average", "Poor" }));
        cmbEndurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnduranceActionPerformed(evt);
            }
        });

        cmbMentalFocus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbMentalFocus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Highly Focused", "Focused", "Distracted", "Highly Distracted" }));
        cmbMentalFocus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMentalFocusActionPerformed(evt);
            }
        });

        lblMentalFocus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMentalFocus.setForeground(new java.awt.Color(255, 255, 255));
        lblMentalFocus.setText("Mental Focus:");

        lblPerformanceScore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPerformanceScore.setForeground(new java.awt.Color(255, 255, 255));
        lblPerformanceScore.setText("Performance Score:");

        sliderPerformanceScore.setMajorTickSpacing(1);
        sliderPerformanceScore.setMaximum(10);
        sliderPerformanceScore.setMinimum(1);
        sliderPerformanceScore.setValue(5);

        tblPerformance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblPerformance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Game Played", "Speed", "Endurance", "Strength", "Mental Focus", "Performance Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPerformance);

        cmbStudents.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbStudents.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStudentsActionPerformed(evt);
            }
        });

        btnRecord.setBackground(new java.awt.Color(153, 153, 255));
        btnRecord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnRecord.setText("Record");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(136, 136, 136)
                        .addComponent(lblRecordPerformance))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderPerformanceScore, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSpeed, 0, 294, Short.MAX_VALUE)
                            .addComponent(lblSpeed)
                            .addComponent(lblEndurance)
                            .addComponent(cmbEndurance, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGamePlayed)
                            .addComponent(cmbGamePlayed, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStrength)
                            .addComponent(cmbStrength, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMentalFocus, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMentalFocus)
                            .addComponent(btnRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblStudentName)
                    .addComponent(lblPerformanceScore))
                .addGap(0, 58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbEndurance, cmbSpeed, cmbStudents});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblRecordPerformance))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStudentName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGamePlayed)
                        .addGap(11, 11, 11)
                        .addComponent(cmbGamePlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSpeed)
                        .addGap(3, 3, 3)
                        .addComponent(cmbSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEndurance)
                        .addGap(2, 2, 2)
                        .addComponent(cmbEndurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStrength)
                        .addGap(3, 3, 3)
                        .addComponent(cmbStrength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMentalFocus)
                        .addGap(2, 2, 2)
                        .addComponent(cmbMentalFocus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(lblPerformanceScore)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderPerformanceScore, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGamePlayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGamePlayedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGamePlayedActionPerformed

    private void cmbMentalFocusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMentalFocusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMentalFocusActionPerformed

    private void cmbEnduranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnduranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEnduranceActionPerformed

    private void cmbStrengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStrengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStrengthActionPerformed

    private void cmbSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSpeedActionPerformed

    private void populatePerformanceTable2(Student selectedStudent) {
        DefaultTableModel model = (DefaultTableModel) tblPerformance.getModel();
        model.setRowCount(0); // Clear existing rows

        Map<String, Map<String, String>> performances = selectedStudent.getGamePerformances();

        for (Map.Entry<String, Map<String, String>> gameEntry : performances.entrySet()) {
            String gameName = gameEntry.getKey();
            Map<String, String> performance = gameEntry.getValue();

            String performanceScore = performance.get("PerformanceScore");
            if (performanceScore == null || performanceScore.isEmpty()) {
                performanceScore = "0"; // Assign a default value
            }

            // Retrieve performance attributes
            String speed = performance.getOrDefault("Speed", null);
            String strength = performance.getOrDefault("Strength", null);
            String endurance = performance.getOrDefault("Endurance", null);
            String mentalFocus = performance.getOrDefault("MentalFocus", null);

            // String performanceScore = performance.getOrDefault("PerformanceScore", performanceScore1);
            // Ensure performanceScore is parsable
            int parsedScore = 0;
            try {
                parsedScore = Integer.parseInt(performanceScore);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid performance score for game: " + gameName, "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Add a row to the table
            Object[] row = new Object[]{
                selectedStudent.getName(), // Student Name
                gameName, // Game Name
                speed, // Speed
                strength, // Strength
                endurance, // Endurance
                mentalFocus, // Mental Focus
                parsedScore,};
            model.addRow(row);
        }
    }

    private void populatePerformanceTable(Student selectedstudent) {
        // Get the selected student's name from the combo box
        String selectedStudentName = cmbStudents.getSelectedItem().toString();
        if (selectedStudentName == null || selectedStudentName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a student.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Fetch the table model
        DefaultTableModel model = (DefaultTableModel) tblPerformance.getModel();
        model.setRowCount(0); // Clear existing rows

        // Find the selected student from the organization
        Organization org = system.getOrganizationDirectory().findOrganization(Organization.Type.Student);
        if (org == null) {
            JOptionPane.showMessageDialog(this, "Student organization not found!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Fetch the student list and find the matching student
        ArrayList<Student> studentList = org.getStudentDirectory().getStudentList();
        Student selectedStudent = null;
        for (Student student : studentList) {
            if (student.getName().equals(selectedStudentName)) {
                selectedStudent = student;
                break;
            }
        }

        // Validate that the selected student exists
        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(this, "Selected student not found!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Populate the table with the selected student's performance data
        String gamePlayed = selectedStudent.getGamePlayed();
        String speed = selectedStudent.getSpeed();
        String endurance = selectedStudent.getEndurance();
        String strength = selectedStudent.getStrength();
        String mentalFocus = selectedStudent.getMentalFocus();
        int performanceScore = selectedStudent.getPerformanceScore();
//    String coachComments = selectedStudent.getCoachComments();

        // Add the data to the table
        Object[] row = new Object[]{
            selectedStudent.getName(), // Student Name
            gamePlayed, // Game Played
            speed, // Speed
            endurance, // Endurance
            strength, // Strength
            mentalFocus, // Mental Focus
            performanceScore, // Performance Score
        //        coachComments               // Coach's Comments
        };
        model.addRow(row);
    }


    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Navigate back to the SportsCoachWorkAreaJPanel
        SportsCoachWorkAreaJPanel pwajp = new SportsCoachWorkAreaJPanel(splitPane, account, system, system);
        splitPane.setRightComponent(pwajp);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStudentsActionPerformed
        // TODO add your handling code here:
        Student selectedStudent = (Student) cmbStudents.getSelectedItem();

        if (selectedStudent != null) {
//            populatePerformanceTable(selectedStudent);
            populatePerformanceTable2(selectedStudent);
        }
    }//GEN-LAST:event_cmbStudentsActionPerformed

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
        // TODO add your handling code here:
        try {
            // Get the selected student from the combo box
            String selectedStudentName = cmbStudents.getSelectedItem().toString();

            if (selectedStudentName == null || selectedStudentName.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please select a student.");
                return;
            }

            // Find the selected student from the organization
            Organization org = system.getOrganizationDirectory().findOrganization(Organization.Type.Student);
            if (org == null) {
                JOptionPane.showMessageDialog(this, "Student organization not found!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ArrayList<Student> studentList = org.getStudentDirectory().getStudentList();
            Student selectedStudent = null;

            for (Student student : studentList) {
                if (student.getName().equals(selectedStudentName)) {
                    selectedStudent = student;
                    break;
                }
            }

            if (selectedStudent == null) {
                JOptionPane.showMessageDialog(this, "Selected student not found!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Retrieve inputs from the form
            String gamePlayed = cmbGamePlayed.getSelectedItem().toString();
            String speed = cmbSpeed.getSelectedItem().toString();
            String endurance = cmbEndurance.getSelectedItem().toString();
            String strength = cmbStrength.getSelectedItem().toString();
            String mentalFocus = cmbMentalFocus.getSelectedItem().toString();
            int performanceScore = sliderPerformanceScore.getValue();

//        String coachComments = txtCoachsComment.getText().trim();
            // Validate inputs
            if (gamePlayed.isEmpty() || speed.isEmpty() || endurance.isEmpty() || strength.isEmpty() || mentalFocus.isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields must be filled in.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Retrieve inputs from the form
            // Update the student's performance data
            Map<String, String> performance = new HashMap<>();
            performance.put("Speed", speed);
            performance.put("Endurance", endurance);
            performance.put("Strength", strength);
            performance.put("MentalFocus", mentalFocus);
            performance.put("PerformanceScore", String.valueOf(performanceScore));
            selectedStudent.addGamePerformance(gamePlayed, performance);

      // Update the student's performance data
            // Confirmation message
            JOptionPane.showMessageDialog(this, "Performance data saved successfully!");

            // Refresh the table with the updated performance data
            populatePerformanceTable2(selectedStudent);

            // Clear inputs after submission (optional)
            cmbGamePlayed.setSelectedIndex(0);
            cmbSpeed.setSelectedIndex(0);
            cmbEndurance.setSelectedIndex(0);
            cmbStrength.setSelectedIndex(0);
            cmbMentalFocus.setSelectedIndex(0);
            sliderPerformanceScore.setValue(50); // Reset slider to default value


        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred while saving performance data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnRecordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRecord;
    private javax.swing.JComboBox<String> cmbEndurance;
    private javax.swing.JComboBox<String> cmbGamePlayed;
    private javax.swing.JComboBox<String> cmbMentalFocus;
    private javax.swing.JComboBox<String> cmbSpeed;
    private javax.swing.JComboBox<String> cmbStrength;
    private javax.swing.JComboBox cmbStudents;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEndurance;
    private javax.swing.JLabel lblGamePlayed;
    private javax.swing.JLabel lblMentalFocus;
    private javax.swing.JLabel lblPerformanceScore;
    private javax.swing.JLabel lblRecordPerformance;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblStrength;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JSlider sliderPerformanceScore;
    private javax.swing.JTable tblPerformance;
    // End of variables declaration//GEN-END:variables
}
