/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.SportsCoachRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Roles.StudentRole;
import Business.Student.Student;
import Business.Student.StudentDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import ui.LoginScreen;
import ui.Organization.SportsEventManagerRole.OrganizeEventsJPanel;

/**
 *
 * @author bbpri
 */
public class SportsCoachWorkAreaJPanel extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;
    private StudentDirectory studentlist;
//    private Student student;

    /**
     * Creates new form SportsCoachWorkAreaJPanel
     */
    public SportsCoachWorkAreaJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane = splitPane;
        this.account = account;
        this.organization = organization;
        this.system = system;
        Organization studentOrganization = system.getOrganizationDirectory().findOrganization(Organization.Type.Student);

        if (studentOrganization == null) {
            JOptionPane.showMessageDialog(null, "Student organization does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

// Use the existing StudentDirectory
        studentlist = studentOrganization.getStudentDirectory();
        System.out.println("Students list ************************" + studentlist.getStudentList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecordPerformance = new javax.swing.JButton();
        btnCollaborate = new javax.swing.JButton();
        lblDoctorEnterprise = new javax.swing.JLabel();
        btnCommunicate = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        btnRecordPerformance.setBackground(new java.awt.Color(153, 153, 255));
        btnRecordPerformance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRecordPerformance.setForeground(new java.awt.Color(255, 255, 255));
        btnRecordPerformance.setText("Record Performance");
        btnRecordPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordPerformanceActionPerformed(evt);
            }
        });

        btnCollaborate.setBackground(new java.awt.Color(153, 153, 255));
        btnCollaborate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCollaborate.setForeground(new java.awt.Color(255, 255, 255));
        btnCollaborate.setText("Collaborate with Healthcare Professionals");
        btnCollaborate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollaborateActionPerformed(evt);
            }
        });

        lblDoctorEnterprise.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblDoctorEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoctorEnterprise.setText("Sports Coach");

        btnCommunicate.setBackground(new java.awt.Color(153, 153, 255));
        btnCommunicate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCommunicate.setForeground(new java.awt.Color(255, 255, 255));
        btnCommunicate.setText("Communicate with Parents/Teachers");
        btnCommunicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunicateActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 153, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDoctorEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnRecordPerformance)
                    .addComponent(btnCollaborate)
                    .addComponent(btnCommunicate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorEnterprise)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnRecordPerformance)
                .addGap(34, 34, 34)
                .addComponent(btnCollaborate)
                .addGap(35, 35, 35)
                .addComponent(btnCommunicate)
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCollaborateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollaborateActionPerformed
        // TODO add your handling code here:   
        if (studentlist.getStudentList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student does not exist. Register the student first", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CollaborateWithHealthcareJPanel pwajp = new CollaborateWithHealthcareJPanel(splitPane, account, system, system);
        splitPane.setRightComponent(pwajp);

    }//GEN-LAST:event_btnCollaborateActionPerformed

    private void btnCommunicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunicateActionPerformed
        // TODO add your handling code here:                                            
        // Switch to the CommunicateJPanel
        if (studentlist.getStudentList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student does not exist. Register the student first", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CommunicateJPanel pwajp = new CommunicateJPanel(splitPane, account, system, system);
        splitPane.setRightComponent(pwajp);

    }//GEN-LAST:event_btnCommunicateActionPerformed

    private void btnRecordPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordPerformanceActionPerformed
        // TODO add your handling code here:     
        if (studentlist.getStudentList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student does not exist. Register the student first", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        RecordPerformanceJPanel pwajp = new RecordPerformanceJPanel(splitPane, account, system, system);
        splitPane.setRightComponent(pwajp);

    }//GEN-LAST:event_btnRecordPerformanceActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginScreen login = new LoginScreen(splitPane, system);
        splitPane.setRightComponent(login);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCollaborate;
    private javax.swing.JButton btnCommunicate;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRecordPerformance;
    private javax.swing.JLabel lblDoctorEnterprise;
    // End of variables declaration//GEN-END:variables
}
