/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Enterprise.Nutritionist;

import Business.Business.EcoSystem;
import Business.Organization.NutritionistOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NutritionistChatWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bbpri
 */
public class NutritionistChatWithParent extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private UserAccount sender;
    private Organization organization;
    private EcoSystem system;
    NutritionistChatWorkRequest nutritionistChatWorkRequest;

    /**
     * Creates new form NutritionistChatWithParent
     */
    public NutritionistChatWithParent(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        this.splitPane = splitPane;
        this.sender = account;
        this.organization = organization;
        System.out.println("*NutritionistChat parent workarea j panel constructure "+organization);
        this.system = system;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequest = new javax.swing.JTable();
        btnAssignSelf = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResolution = new javax.swing.JTextArea();
        lblResolution = new javax.swing.JLabel();
        btnback1 = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Chat With Parent");

        tblWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Reciver", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblWorkRequest);

        btnAssignSelf.setText("Assign to me");
        btnAssignSelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignSelfActionPerformed(evt);
            }
        });

        txtResolution.setColumns(20);
        txtResolution.setRows(5);
        jScrollPane2.setViewportView(txtResolution);

        lblResolution.setText("Resolution");

        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssignSelf)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblResolution)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSend))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnback1)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnback1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnAssignSelf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblResolution)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSend)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        NutritionistsWorkAreaJPanel nwajp = new NutritionistsWorkAreaJPanel(splitPane, sender, system, system);
        splitPane.setRightComponent(nwajp);
    }//GEN-LAST:event_btnback1ActionPerformed

    private void btnAssignSelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignSelfActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWorkRequest.getSelectedRow();

        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) tblWorkRequest.getValueAt(selectedRow, 0);
            if (request.getMessage().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already acknowledged and completed.");
                return;
            } else {
                request.setReceiver(sender);
                request.setStatus("Assigned");

                populateTable();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Choose a reuest to acknowledge.");
            return;
        }
    }//GEN-LAST:event_btnAssignSelfActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        System.out.println("Inside acknowledge");
        int selectedRow = tblWorkRequest.getSelectedRow();
        if (selectedRow >= 0) {
            nutritionistChatWorkRequest = (NutritionistChatWorkRequest) tblWorkRequest.getValueAt(selectedRow, 0);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a request message to process.");
            return;
        }
        
        if (txtResolution.getText().equals("") || txtResolution.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a resolution to send.");
            return;
        }
        
        
        nutritionistChatWorkRequest.setResultMessage(txtResolution.getText());
        nutritionistChatWorkRequest.setStatus("Resolved");
        populateTable();
        JOptionPane.showMessageDialog(null, "Message processed");
        
    }//GEN-LAST:event_btnSendActionPerformed

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblWorkRequest.getModel();

        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestNutritionList()) {
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getParent() == null ? null : request.getSender().getParent().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();

            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignSelf;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnback1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblResolution;
    private javax.swing.JTable tblWorkRequest;
    private javax.swing.JTextArea txtResolution;
    // End of variables declaration//GEN-END:variables
}
