/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.SportsCoachRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author nanaabena
 */
public class CollaborateWithHealthcareJPanel extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;
     
    /**
     * Creates new form CollaborateWithHealthcareJPanel
     */
    public CollaborateWithHealthcareJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        this.account=account;
        this.organization=organization;
        this.system=system;
//    populateStudentDetails();
}
        /**
     * Populates the student details in the respective fields.
     */
    
//    private void populateStudentDetails() {
//    if (student != null) {
//        txtStudentName.setText(student.getName());
//        txtStudentSport.setText(student.getSportsParticipation());
//    } else {
//        JOptionPane.showMessageDialog(this, "No student data available!");
//    }
//}

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStudentName = new javax.swing.JTextField();
        lblStudentName = new javax.swing.JLabel();
        lblStudentSport = new javax.swing.JLabel();
        txtStudentSport = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChatDisplay = new javax.swing.JTextArea();
        lblStudentSport1 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblStudentSport2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        txtStudentName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        lblStudentName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentName.setText("Student's Name:");

        lblStudentSport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentSport.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentSport.setText("Student's Sport(s):");

        txtStudentSport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSend.setBackground(new java.awt.Color(153, 153, 255));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Collaborate with Healthcare Professionals");

        txtChatDisplay.setColumns(20);
        txtChatDisplay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtChatDisplay.setRows(5);
        jScrollPane1.setViewportView(txtChatDisplay);

        lblStudentSport1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentSport1.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentSport1.setText("Chat Display:");

        txtMessage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(153, 153, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");

        lblStudentSport2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentSport2.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentSport2.setText("Message:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStudentSport)
                    .addComponent(lblStudentName)
                    .addComponent(lblStudentSport1)
                    .addComponent(lblStudentSport2))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMessage)
                    .addComponent(jScrollPane1)
                    .addComponent(txtStudentName)
                    .addComponent(txtStudentSport, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentSport, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentSport))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblStudentSport1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentSport2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        // Get the typed message
//        String message = txtMessage.getText().trim();
//
//        // Validate that the message is not empty
//        if (message.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Please enter a message before sending.");
//            return;
//        }
//        
//        // Append the message to chat history
//        chatHistory.add("You: " + message);
//
//        // Simulate a response from a healthcare professional (optional)
//        chatHistory.add("Doctor: Thank you for your message. We'll get back to you shortly.");
//
//        // Update the chat display
//        updateChatDisplay();
//
//        // Clear the message field
//        txtMessage.setText("");
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        SportsCoachWorkAreaJPanel pwajp = new SportsCoachWorkAreaJPanel(splitPane,account,system ,system);
        splitPane.setRightComponent(pwajp);
    }//GEN-LAST:event_btnBackActionPerformed

        /**
     * Updates the chat display with the current chat history.
     */
//        private void updateChatDisplay() {
//        // Combine chat history into a single string
//        StringBuilder chatBuilder = new StringBuilder();
//        for (String chatMessage : chatHistory) {
//            chatBuilder.append(chatMessage).append("\n");
//        }
//        txtChatDisplay.setText(chatBuilder.toString());
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentSport;
    private javax.swing.JLabel lblStudentSport1;
    private javax.swing.JLabel lblStudentSport2;
    private javax.swing.JTextArea txtChatDisplay;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentSport;
    // End of variables declaration//GEN-END:variables
}
