/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.SportsCoachRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Student.Student;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CoachChatWorkRequest;
import Business.WorkQueue.TeacherChatWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanaabena
 */

   
     
    /**
     * Creates new form CollaborateWithHealthcareJPanel
     */
        
public class CommunicateJPanel extends javax.swing.JPanel {
    
    private JSplitPane splitPane;
    private UserAccount account;
    private Organization organization;
    private EcoSystem system;
    private Student student;

    /**
     * Creates new form CommunicateJPanel
     */
        public CommunicateJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        this.account=account;
        this.organization=organization;
        this.system=system;
        populateStudentDetails();
    }
    
    private void populateStudentDetails() {
    if (student != null) {
        txtStudentName.setText(student.getName());
        txtStudentSport.setText(student.getSportsParticipation());
    } else {
        JOptionPane.showMessageDialog(this, "No student data available!");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCommunicate = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        lblStudentName = new javax.swing.JLabel();
        lblStudentSport = new javax.swing.JLabel();
        txtStudentSport = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCoachsResponse = new javax.swing.JTextArea();
        lblTeacher = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblCoach = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTeacherMessage = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        lblCommunicate.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblCommunicate.setForeground(new java.awt.Color(255, 255, 255));
        lblCommunicate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCommunicate.setText("Communicate with Teacher");

        txtStudentName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        lblStudentName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentName.setText("Student's Name:");

        lblStudentSport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentSport.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentSport.setText("Student's Sport(s):");

        txtStudentSport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtStudentSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentSportActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSend.setBackground(new java.awt.Color(153, 153, 255));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        txtCoachsResponse.setColumns(20);
        txtCoachsResponse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCoachsResponse.setRows(5);
        jScrollPane1.setViewportView(txtCoachsResponse);

        lblTeacher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTeacher.setForeground(new java.awt.Color(255, 255, 255));
        lblTeacher.setText("Teacher's Message:");

        btnSave.setBackground(new java.awt.Color(153, 153, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblCoach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCoach.setForeground(new java.awt.Color(255, 255, 255));
        lblCoach.setText("Coach's Message:");

        tblTeacherMessage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblTeacherMessage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Status", "Response"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTeacherMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCoach)
                                .addGap(59, 59, 59)
                                .addComponent(jScrollPane1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStudentName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStudentSport)
                                    .addComponent(txtStudentSport, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(26, 26, 26)
                                .addComponent(lblCommunicate))
                            .addComponent(lblTeacher))
                        .addContainerGap(109, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCommunicate)
                            .addComponent(btnBack))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentName)
                            .addComponent(lblStudentSport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentSport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblTeacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblCoach))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
                                      
    DefaultTableModel model = (DefaultTableModel) tblTeacherMessage.getModel();
    model.setRowCount(0);

    for (WorkRequest request : organization.getWorkQueue().getWorkRequestTeacherList()) {
        if (request instanceof TeacherChatWorkRequest) {
            TeacherChatWorkRequest teacherRequest = (TeacherChatWorkRequest) request;

            Object[] row = new Object[]{
                teacherRequest,                      // Message object (toString() will display message)
                teacherRequest.getSender().getUsername(), // Sender username
                teacherRequest.getStatus(),         // Status of the request
                teacherRequest.getResultMessage()   // Response (if any)
            };
            model.addRow(row);
        }
    }


    }//GEN-LAST:event_btnSendActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
//        // TODO add your handling code here:
    try {
        // Get the selected WorkRequest from the table
        int selectedRow = tblTeacherMessage.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a message to respond to.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Retrieve the TeacherChatWorkRequest
        DefaultTableModel model = (DefaultTableModel) tblTeacherMessage.getModel();
        TeacherChatWorkRequest teacherRequest = (TeacherChatWorkRequest) model.getValueAt(selectedRow, 0);

        // Create a new CoachChatWorkRequest to store the coach's response
        CoachChatWorkRequest coachResponse = new CoachChatWorkRequest();
        coachResponse.setSender(account); // Sender is the logged-in coach
        coachResponse.setReceiver(teacherRequest.getSender()); // Receiver is the teacher who sent the message
        coachResponse.setMessage(txtCoachsResponse.getText().trim()); // Set coach's response message
        coachResponse.setStatus("Responded");
        coachResponse.setRequestDate(LocalDate.now());

        // Update the teacher's request with the response
        teacherRequest.setResultMessage(txtCoachsResponse.getText().trim());
        teacherRequest.setResolveDate(new Date());
        teacherRequest.setStatus("Responded");

        // Add the response to the coach's queue (optional, depends on your use case)
        organization.getWorkQueue().getWorkRequestTeacherList().add(coachResponse);

        // Update the table
        model.setValueAt("Responded", selectedRow, 2); // Update status in the table

        // Clear the response field
        txtCoachsResponse.setText("");

        JOptionPane.showMessageDialog(this, "Response saved successfully!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saving response: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:                                        
    SportsCoachWorkAreaJPanel pwajp = new SportsCoachWorkAreaJPanel(splitPane,account,system ,system);
        splitPane.setRightComponent(pwajp);

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtStudentSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentSportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentSportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCoach;
    private javax.swing.JLabel lblCommunicate;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentSport;
    private javax.swing.JLabel lblTeacher;
    private javax.swing.JTable tblTeacherMessage;
    private javax.swing.JTextArea txtCoachsResponse;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentSport;
    // End of variables declaration//GEN-END:variables
}
