/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Organization.StudentRole;

import Business.Business.EcoSystem;
import Business.Organization.Organization;
import Business.Roles.StudentRole;
import Business.Roles.TeacherRole;
import Business.Student.Student;
import Business.Student.StudentDirectory;
import Business.UserAccount.UserAccount;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import ui.LoginScreen;
import ui.Organization.TeacherRole.TeacherWorkAreaJPanel;
import ui.ViewSportsEventsJPanel;

/**
 *
 * @author bbpri
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {
    private JSplitPane splitPane;
    private UserAccount student;
    private Organization organization;
    private EcoSystem system;
    private ImageIcon finalImg;

    /**
     * Creates new form StudentWorkAreaJPanel
     */
    public StudentWorkAreaJPanel(JSplitPane splitPane, UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.splitPane=splitPane;
        this.student=account;
        this.organization=organization;
        this.system=system;
        System.out.println(account.getStudent().getName());
        String name = account.getStudent().getName();
        txtName.setText(student.getStudent().getName());
//        int age = Integer.parseInt(txtAge.getText());
        txtAge.setText(String.valueOf(student.getStudent().getAge()));
        txtGender.setText(student.getStudent().getGender());
        txtPName.setText(student.getStudent().getParentname());
        txtPNo.setText(student.getStudent().getParentphno());
        System.out.println("*******"+student.getStudent().getHeight());
        System.out.println("***********"+student.getStudent().getWeight());
        txtHt.setText(String.valueOf(student.getStudent().getHeight()));
        txtWt.setText(String.valueOf(student.getStudent().getWeight()));
         if (student.getStudent().getLogoImage()!=null)
            lblImage.setIcon(student.getStudent().getLogoImage());
        else
             lblImage.setText("No Logo");
//      To display parents name in student workarea panel        
//        Student currentStudent = student.getStudent();
//
//        if(currentStudent!=null && currentStudent.getParent()!=null){
//            String pname=currentStudent.getParent().getName();
//            System.out.println("name of parent "+pname);
//            lblpname.setText(pname);
//        }else{
//            lblpname.setText("Parent name : not assigned");
//        }

//        if (student.getStudent().getLogoImage()!=null)
//            finalImg.se
//                    setImage(student.getStudent().getLogoImage());
//        else
//            student.setText("No Logo");
        
       

//        System.out.println(student.getGrade());
//        JOptionPane.showMessageDialog(this, "Student Registered successfully!");

//         if (Student.getLogoImage()!=null)
//            imgLogo.setIcon(Student.getLogoImage());
//        else
//            imgLogo.setText("No Logo");
//        System.out.println(account.getStudent().getName());
        System.out.println(account.getStudent().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPid = new javax.swing.JTextField();
        lblPName = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtPNo = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        lblPhno = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        Gender = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtPName = new javax.swing.JTextField();
        btnViewAcademicProgress = new javax.swing.JButton();
        btnViewSportsEvents = new javax.swing.JButton();
        txtWt = new javax.swing.JTextField();
        lblEmail2 = new javax.swing.JLabel();
        txtHt = new javax.swing.JTextField();
        lblEmail3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student's Dashboard");

        txtPid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPid.setEnabled(false);

        lblPName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPName.setForeground(new java.awt.Color(255, 255, 255));
        lblPName.setText("Parent Name");

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Id");

        txtPNo.setEditable(false);
        txtPNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblImage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("<No Image>");

        lblPhno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhno.setForeground(new java.awt.Color(255, 255, 255));
        lblPhno.setText("Phone no");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age");

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Gender.setForeground(new java.awt.Color(255, 255, 255));
        Gender.setText("Gender");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");

        txtGender.setEditable(false);
        txtGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnLogout.setBackground(new java.awt.Color(153, 153, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtPName.setEditable(false);
        txtPName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnViewAcademicProgress.setBackground(new java.awt.Color(153, 153, 255));
        btnViewAcademicProgress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewAcademicProgress.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAcademicProgress.setText("View Academic Progress");
        btnViewAcademicProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAcademicProgressActionPerformed(evt);
            }
        });

        btnViewSportsEvents.setBackground(new java.awt.Color(153, 153, 255));
        btnViewSportsEvents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewSportsEvents.setForeground(new java.awt.Color(255, 255, 255));
        btnViewSportsEvents.setText("View Sports Events");
        btnViewSportsEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSportsEventsActionPerformed(evt);
            }
        });

        txtWt.setEditable(false);
        txtWt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblEmail2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail2.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail2.setText("Height");

        txtHt.setEditable(false);
        txtHt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblEmail3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail3.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail3.setText("Weight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPid, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Gender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(btnViewAcademicProgress))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPName)
                                    .addComponent(lblPhno, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPNo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHt, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(txtWt))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnViewSportsEvents)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnLogout)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhno)))
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail2)
                    .addComponent(txtHt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail3)
                    .addComponent(txtWt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAcademicProgress)
                    .addComponent(btnViewSportsEvents))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginScreen liui = new LoginScreen(splitPane, system);
        splitPane.setRightComponent(liui);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewAcademicProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAcademicProgressActionPerformed
        // TODO add your handling code here:
        ViewAcademicProgressJPanel vapjp=new ViewAcademicProgressJPanel(splitPane, student, organization, system);
        splitPane.setRightComponent(vapjp);
    }//GEN-LAST:event_btnViewAcademicProgressActionPerformed

    private void btnViewSportsEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSportsEventsActionPerformed
        // TODO add your handling code here:
        ViewSportsEventsJPanel vapjp=new ViewSportsEventsJPanel(splitPane, student, organization, system);
        splitPane.setRightComponent(vapjp);
    }//GEN-LAST:event_btnViewSportsEventsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gender;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewAcademicProgress;
    private javax.swing.JButton btnViewSportsEvents;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEmail3;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPName;
    private javax.swing.JLabel lblPhno;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHt;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtPNo;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtWt;
    // End of variables declaration//GEN-END:variables
}
